// CHINESE — 95 questions, auto-generated from batch_*.json
// Last updated: 2026-04-13

export default [
  {
    "id": "chinese-026",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字音"],
    "question": "加点字读音相同的一项是：",
    "options": ["千载(zai)/记载(zai)", "兴(xing)奋/兴(xing)旺", "缝(feng)补/缝隙(xi)", "尽头(jin)/尽职(jin)"],
    "answer": "千载(zai)/记载(zai)",
    "explanation": "千载和记载都读zai",
  },
  {
    "id": "chinese-027",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["病句修改"],
    "question": "下列句子有语病的是：",
    "options": ["通过这次活动，我学到了很多知识。", "我们要继承和发扬勤俭节约的优良传统。", "他多么平凡，像草一样。", "我多么希望早点见到我的妈妈啊！"],
    "answer": "我多么希望早点见到我的妈妈啊！",
    "explanation": "多么和希望搭配不当，应为多么希望表达愿望而非感叹程度",
  },
  {
    "id": "chinese-028",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "下列词语中加点字解释正确的是：",
    "options": ["喜出望外(盼望)", "不计其数(计算)", "完璧归赵(完整的)", "抑扬顿挫(挫败)"],
    "answer": "喜出望外(盼望)",
    "explanation": "喜出望外：意料之外的喜悦，含有盼望、期待的意思",
  },
  {
    "id": "chinese-029",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "春风得意，_____。",
    "answer": "骏马奔驰",
    "explanation": "出自孟郊《登科后》，全诗：昔日龌龊不足夸，今朝放荡思无涯。春风得意马蹄疾，一日看尽长安花。",
  },
  {
    "id": "chinese-030",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列词语书写完全正确的是：",
    "options": ["谈笑风声 走投无路", "再接再厉 守株待兔", "精兵简政 汗流浃背", "直接了当 变本加厉"],
    "answer": "精兵简政 汗流浃背",
    "explanation": "谈笑风声应为生，走投无路应为投，直接了当应为截，变本加厉应为厉",
  },
  {
    "id": "chinese-031",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "下列古诗句中使用了比喻修辞的是：",
    "options": ["飞流直下三千尺，疑是银河落九天。", "不知细叶谁裁出，二月春风似剪刀。", "举头望明月，低头思故乡。", "海内存知己，天涯若比邻。"],
    "answer": "不知细叶谁裁出，二月春风似剪刀。",
    "explanation": "把春风比作剪刀，是比喻修辞中的明喻",
  },
  {
    "id": "chinese-032",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "下列句子中顿号使用正确的是：",
    "options": ["我喜爱足球、篮球、乒乓球、羽毛球、等体育运动。", "我们的父母、老师、同学，都关心我们的成长。", "今天，明天、后天都有空。", "她买了水果、苹果、和葡萄。"],
    "answer": "我们的父母、老师、同学，都关心我们的成长。",
    "explanation": "并列词语之间用顿号，但A等前不加顿号；C层次混乱；D连续停顿用顿号而非和",
  },
  {
    "id": "chinese-033",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "下列作者与作品对应有误的是：",
    "options": ["老舍——《骆驼祥子》", "朱自清——《春》", "鲁迅——《藤野先生》", "冰心——《繁星·春水》"],
    "answer": "鲁迅——《藤野先生》",
    "explanation": "《藤野先生》选自鲁迅的《朝花夕拾》，藤野先生是日本人，但作品是正确的",
  },
  {
    "id": "chinese-034",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "依次填入横线正确的一项是：他_____跑得真快，_____像一阵风。",
    "options": ["这么...这", "简直...简直", "真...这", "简直...这"],
    "answer": "简直...简直",
    "explanation": "简直表示完全如此，语气强烈，后一分句像一阵风是比喻",
  },
  {
    "id": "chinese-035",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "会当凌绝顶，_____。",
    "answer": "一览众山小",
    "explanation": "出自杜甫《望岳》：荡胸生层云，决眦入归鸟。会当凌绝顶，一览众山小。",
  },
  {
    "id": "chinese-036",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字音"],
    "question": "下列词语中加点字读音正确的是：",
    "options": ["纤(xian)细 歼(jian)灭", "纤(xian)细 歼(qian)灭", "纤(qian)细 歼(jian)灭", "纤(qian)细 歼(qian)灭"],
    "answer": "纤(xian)细 歼(jian)灭",
    "explanation": "纤读xian，歼读jian；A正确，B歼读qian错误，C纤读qian错误",
  },
  {
    "id": "chinese-037",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《天净沙·秋思》中夕阳西下的下一句是：",
    "options": ["断肠人在天涯", "古道西风瘦马", "小桥流水人家", "枯藤老树昏鸦"],
    "answer": "断肠人在天涯",
    "explanation": "马致远《天净沙·秋思》：枯藤老树昏鸦，小桥流水人家，古道西风瘦马。夕阳西下，断肠人在天涯。",
  },
  {
    "id": "chinese-038",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词性辨析"],
    "question": "下列词语中与咚咚地响结构相同的是：",
    "options": ["隆隆的雷声", "认真地学习", "轻轻地飘", "勇敢的战士"],
    "answer": "轻轻地飘",
    "explanation": "都是状语+地+动词结构",
  },
  {
    "id": "chinese-039",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "下列不属于唐代诗人的是：",
    "options": ["杜甫", "白居易", "王安石", "李商隐"],
    "answer": "王安石",
    "explanation": "王安石是北宋文学家，唐代诗人有李白、杜甫、白居易、李商隐等",
  },
  {
    "id": "chinese-040",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "两岸猿声啼不住，_____。",
    "answer": "轻舟已过万重山",
    "explanation": "出自李白《早发白帝城》：朝辞白帝彩云间，千里江陵一日还。两岸猿声啼不住，轻舟已过万重山。",
  },
  {
    "id": "chinese-041",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列没有错别字的一项是：",
    "options": ["三年自然灾害", "穿流不息", "不记其数", "默不作声"],
    "answer": "三年自然灾害",
    "explanation": "川流不息应为川，不计其数应为记，默默不作声应为默",
  },
  {
    "id": "chinese-042",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《卖炭翁》中可怜身上衣正单的下一句是：",
    "options": ["心忧炭贱愿天寒", "半匹红纱一丈绫", "宫使驱将惜不得", "夜来城外一尺雪"],
    "answer": "心忧炭贱愿天寒",
    "explanation": "虽身上衣单，但天寒炭价才能高，反映卖炭翁矛盾心理",
  },
  {
    "id": "chinese-043",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "下列句子中使用了拟人修辞的是：",
    "options": ["红的像火，粉的像霞。", "桃树、杏树、梨树，你不让我，我不让你。", "春天像刚落地的娃娃。", "太阳像火球。"],
    "answer": "桃树、杏树、梨树，你不让我，我不让你。",
    "explanation": "把花当作人来写，是拟人，A和C是比喻，D是比喻",
  },
  {
    "id": "chinese-044",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "轻在轻轻的风中的意思是：",
    "options": ["重量小", "柔和", "不重要", "缓慢"],
    "answer": "柔和",
    "explanation": "轻风指柔和的风，这里轻形容风的柔和程度",
  },
  {
    "id": "chinese-045",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "请写出《观沧海》中描写草木的句子：",
    "answer": "树木丛生，百草丰茂。",
    "explanation": "曹操《观沧海》：东临碣石，以观沧海。水何澹澹，山岛竦峙。树木丛生，百草丰茂。秋风萧瑟，洪波涌起。",
  },
  {
    "id": "chinese-046",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "下列不属于四大名著的是：",
    "options": ["《三国演义》", "《水浒传》", "《儒林外史》", "《红楼梦》"],
    "answer": "《儒林外史》",
    "explanation": "四大名著：《三国演义》《水浒传》《西游记》《红楼梦》。《儒林外史》是清代吴敬梓的作品",
  },
  {
    "id": "chinese-047",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "给下列句子加标点，正确的一项是：",
    "options": ["我说：你去，你去！", "我说你去，你去。", "我说：你去，你去。", "我说你去，你去？"],
    "answer": "我说：你去，你去。",
    "explanation": "直接引语时，说话人在前用冒号，引用内容正常标点",
  },
  {
    "id": "chinese-048",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "人生自古谁无死，留取丹心照汗青的作者是：",
    "options": ["文天祥", "岳飞", "辛弃疾", "陆游"],
    "answer": "文天祥",
    "explanation": "出自文天祥《过零丁洋》，表现了崇高的爱国精神",
  },
  {
    "id": "chinese-049",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "出淤泥而不染，_____。",
    "answer": "濯清涟而不妖",
    "explanation": "出自周敦颐《爱莲说》，描写莲花的品质，出淤泥而不染，濯清涟而不妖",
  },
  {
    "id": "chinese-050",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字音"],
    "question": "加点字读音相同的一组是：",
    "options": ["涨chao/涨zhang红脸", "着急zhao/着mi迷", "勉强qiang/强qiang词夺理", "仿佛fo/佛fo祖"],
    "answer": "勉强qiang/强qiang词夺理",
    "explanation": "勉强qiang，强qiang词夺理；涨chao/涨zhang；着急zhao/着mi；仿佛fo/佛fu",
  },
  {
    "id": "chinese-051",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "顾在三顾茅庐中的意思是：",
    "options": ["注意", "拜访", "回头看", "关心"],
    "answer": "拜访",
    "explanation": "三顾茅庐：三次拜访刘备请诸葛亮出山，顾是拜访的意思",
  },
  {
    "id": "chinese-052",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "遥望洞庭山水翠，白银盘里一青螺使用了：",
    "options": ["比喻", "夸张", "对偶", "借代"],
    "answer": "比喻",
    "explanation": "把洞庭湖比作白银盘，把君山比作青螺",
  },
  {
    "id": "chinese-053",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "大漠孤烟直，_____。",
    "answer": "长河落日圆",
    "explanation": "出自王维《使至塞上》，描写边塞壮阔景象",
  },
  {
    "id": "chinese-054",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《春》是哪位作家的作品？",
    "options": ["鲁迅", "朱自清", "老舍", "冰心"],
    "answer": "朱自清",
    "explanation": "《春》选自《朱自清全集》，是一篇优美的写景散文",
  },
  {
    "id": "chinese-055",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["病句修改"],
    "question": "下列句子没有语病的是：",
    "options": ["我们认真讨论并听取了他的发言。", "他取得了很大进步。", "我不禁忍不住哭了起来。", "经过努力，终于取得了好成绩。"],
    "answer": "他取得了很大进步。",
    "explanation": "A语序不当，应先听取再讨论；C不禁和忍不住重复；D缺少主语",
  },
  {
    "id": "chinese-056",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "走在走马观花中的意思是：",
    "options": ["步行", "跑", "快速移动", "经过"],
    "answer": "跑",
    "explanation": "走马观花：骑在马上看花，走是跑的意思，比喻得意愉快的心情",
  },
  {
    "id": "chinese-057",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "下列诗句中表现思乡之情的是：",
    "options": ["举头望明月，低头思故乡", "独在异乡为异客，每逢佳节倍思亲", "但愿人长久，千里共婵娟", "以上都是"],
    "answer": "以上都是",
    "explanation": "A思故乡，B倍思亲，C共婵娟（团圆），都表达了思乡之情",
  },
  {
    "id": "chinese-058",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列词语中候字写法正确的是：",
    "options": ["气侯", "侯车室", "时候", "无需置疑"],
    "answer": "时候",
    "explanation": "气侯应为候，侯车室应为候，无需置疑应为候，都应写成候",
  },
  {
    "id": "chinese-059",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-句子成分"],
    "question": "下列句子主语是名词的是：",
    "options": ["我们学习语文。", "春天来了。", "认真地做作业。", "跑得很快。"],
    "answer": "春天来了。",
    "explanation": "A我们是指代词；B春天是名词；C是状语+动词短语；D是动词短语",
  },
  {
    "id": "chinese-060",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《三国演义》中草船借箭的主角是：",
    "options": ["刘备", "周瑜", "诸葛亮", "曹操"],
    "answer": "诸葛亮",
    "explanation": "草船借箭是诸葛亮利用大雾天气，用草船向曹操借箭的故事",
  },
  {
    "id": "chinese-061",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "落红不是无情物，_____。",
    "answer": "化作春泥更护花",
    "explanation": "出自龚自珍《己亥杂诗》，以落红化作春泥比喻奉献精神",
  },
  {
    "id": "chinese-062",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "下列句子中引号使用不当的是：",
    "options": ["老师说：要多读书。", "「世上无难事，只要肯登攀」，这是我的座右铭。", "他喜欢读《十万个为什么》。", "李白是诗仙。"],
    "answer": "「世上无难事，只要肯登攀」，这是我的座右铭。",
    "explanation": "直接引语放句中时，前面用逗号，后面句号在引号内，此处引号内外标点颠倒",
  },
  {
    "id": "chinese-063",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "发在发现和理发中的读音：",
    "options": ["fa/fà", "fa/fa", "fa/fà", "fà/fa"],
    "answer": "fa/fà",
    "explanation": "发现fa（产生），理发fa（头发的发，第四声）",
  },
  {
    "id": "chinese-064",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "填空：《塞下曲》中单于夜遁逃的下一句是：",
    "options": ["月黑雁飞高", "欲将轻骑逐", "大雪满弓刀", "林暗草惊风"],
    "answer": "欲将轻骑逐",
    "explanation": "卢纶《塞下曲》：月黑雁飞高，单于夜遁逃。欲将轻骑逐，大雪满弓刀。",
  },
  {
    "id": "chinese-065",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "问渠那得清如许？为有源头活水来使用了什么修辞？",
    "options": ["比喻", "设问", "反问", "夸张"],
    "answer": "设问",
    "explanation": "自问自答，是设问修辞，自问为引起注意，自答为说明道理",
  },
  {
    "id": "chinese-066",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词类活用"],
    "question": "下列句子中词类活用类型不同的是：",
    "options": ["他红着脸说。", "我们要绿化校园。", "狐狸骗了老虎。", "太阳升高了。"],
    "answer": "狐狸骗了老虎。",
    "explanation": "A红是形容词作动词；B绿化是名词作动词；C骗是动词，无活用；D高是形容词作表语，无使动",
  },
  {
    "id": "chinese-067",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《史记》的作者是：",
    "options": ["司马迁", "班固", "陈寿", "范晔"],
    "answer": "司马迁",
    "explanation": "《史记》是我国第一部纪传体通史，作者是西汉史学家司马迁",
  },
  {
    "id": "chinese-068",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《江雪》中千山鸟飞绝的下一句是：",
    "options": ["万径人踪灭", "孤舟蓑笠翁", "独钓寒江雪", "唯见长江天际流"],
    "answer": "万径人踪灭",
    "explanation": "柳宗元《江雪》：千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。",
  },
  {
    "id": "chinese-069",
    "type": "fill",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "旧时王谢堂前燕，_____。",
    "answer": "飞入寻常百姓家",
    "explanation": "出自刘禹锡《乌衣巷》，感叹世事变迁，昔日王谢贵族已衰落",
  },
  {
    "id": "chinese-070",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列词语中叠字书写正确的是：",
    "options": ["高潮迭起", "峰峦叠嶂", "此起彼伏", "重岩叠嶂"],
    "answer": "重岩叠嶂",
    "explanation": "重岩叠嶂（重叠的山崖），嶂和叠都正确；A应为迭，B应为嶂",
  },
  {
    "id": "chinese-071",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-关联词"],
    "question": "_____多读多写，你的作文水平_____会提高。",
    "options": ["只有...才", "只要...就", "因为...所以", "既然...就"],
    "answer": "只要...就",
    "explanation": "条件和结果关系，只要...就...是充分条件句式，有条件就必然有结果",
  },
  {
    "id": "chinese-072",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "胜在名胜古迹和战胜中的意思：",
    "options": ["胜利/胜利", "优美的地方/打赢", "胜利/优美", "优美/打赢"],
    "answer": "优美的地方/打赢",
    "explanation": "名胜古迹：优美的地方；战胜：打赢",
  },
  {
    "id": "chinese-073",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《泊船瓜洲》中春风又绿江南岸的绿字好在哪里？",
    "options": ["写出了春风的色彩和力量", "写出了春天的绿色", "写出了春天到来的迅速", "以上都不对"],
    "answer": "写出了春风的色彩和力量",
    "explanation": "一个绿字形容词用作动词，春风赋予江南以绿色，写出了春风的力量和生机",
  },
  {
    "id": "chinese-074",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "下列句子中省略号使用正确的是：",
    "options": ["我......我不是故意的。", "他低着头说：我......我......", "妈妈叫我：睡觉睡觉！", "我不知道为什么......"],
    "answer": "他低着头说：我......我......",
    "explanation": "引语中表示说话结巴，断断续续，正确使用省略号；A两个句子间应用逗号或句号",
  },
  {
    "id": "chinese-075",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "下列不属于苏轼作品的是：",
    "options": ["《念奴娇·赤壁怀古》", "《水调歌头·明月几时有》", "《题西林壁》", "《醉翁亭记》"],
    "answer": "《醉翁亭记》",
    "explanation": "《醉翁亭记》是欧阳修的作品，苏轼是欧阳修的学生",
  },
  {
    "id": "chinese-076",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《桃花源记》的作者是：",
    "options": ["陶渊明", "周敦颐", "韩愈", "柳宗元"],
    "answer": "陶渊明",
    "explanation": "《桃花源记》是东晋陶渊明的作品，描写了一个与世隔绝的理想社会",
  },
  {
    "id": "chinese-077",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《爱莲说》中菊花的寓意是：",
    "options": ["富贵", "隐逸", "君子", "凡人"],
    "answer": "隐逸",
    "explanation": "陶渊明独爱菊，菊是花中隐士，象征隐居避世的生活态度",
  },
  {
    "id": "chinese-078",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "安在安知鱼之乐中的意思是：",
    "options": ["安全", "怎么", "哪里", "安定"],
    "answer": "怎么",
    "explanation": "安知鱼之乐：怎么知道鱼的快乐，安是疑问代词，怎么",
  },
  {
    "id": "chinese-079",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "山不在高，_____。",
    "options": ["有仙则名", "名不在高", "有龙则灵", "水不在深"],
    "answer": "有仙则名",
    "explanation": "出自刘禹锡《陋室铭》：山不在高，有仙则名；水不在深，有龙则灵",
  },
  {
    "id": "chinese-080",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["病句修改"],
    "question": "下列句子没有语病的是：",
    "options": ["我们必须认真克服并发现工作中的缺点。", "我肯定他会来的。", "经过努力，他终于获得了第一名。", "我不禁忍不住笑了起来。"],
    "answer": "经过努力，他终于获得了第一名。",
    "explanation": "A并列不当，应为先发现再克服；B词语重复；D不禁和忍不住重复",
  },
  {
    "id": "chinese-081",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "下列句子使用了借代修辞的是：",
    "options": ["他的脸红得像苹果。", "解放前中国人民生活在水深火热之中。", "我们要学工学农学兵。", "他把东西一股脑儿倒了出来。"],
    "answer": "解放前中国人民生活在水深火热之中。",
    "explanation": "水深火热借代苦难的生活；A是比喻；C排比；D夸张",
  },
  {
    "id": "chinese-082",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "明月松间照，_____。",
    "options": ["清泉石上流", "明月松间照", "空山新雨后", "天气晚来秋"],
    "answer": "清泉石上流",
    "explanation": "出自王维《山居秋暝》：空山新雨后，天气晚来秋。明月松间照，清泉石上流",
  },
  {
    "id": "chinese-083",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《石壕吏》的作者是：",
    "options": ["李白", "杜甫", "白居易", "王维"],
    "answer": "杜甫",
    "explanation": "《石壕吏》是杜甫的三吏三别之一，描写战争年代人民的苦难",
  },
  {
    "id": "chinese-084",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列词语中正确的是：",
    "options": ["变本加厉", "再接再励", "相形见绌", "随声附合"],
    "answer": "变本加厉",
    "explanation": "再接再厉应为励；相形见绌正确；随声附合应为和",
  },
  {
    "id": "chinese-085",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-关联词"],
    "question": "_____你努力，_____能取得好成绩。",
    "options": ["因为...所以", "只有...才", "如果...就", "既然...就"],
    "answer": "只有...才",
    "explanation": "只有...才...表示必要条件关系，只有努力才能取得好成绩",
  },
  {
    "id": "chinese-086",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《马说》中千里马被埋没的原因是：",
    "options": ["没有伯乐", "不会跑", "吃的太多", "不努力"],
    "answer": "没有伯乐",
    "explanation": "千里马常有而伯乐不常有，千里马因无伯乐赏识而被埋没",
  },
  {
    "id": "chinese-087",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《资治通鉴》的作者是：",
    "options": ["司马光", "司马迁", "班固", "陈寿"],
    "answer": "司马光",
    "explanation": "《资治通鉴》是北宋司马光主编的编年体通史，司马迁的《史记》是纪传体",
  },
  {
    "id": "chinese-088",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "之在先生之乎中的意思是：",
    "options": ["的", "取消句子独立性", "代词他", "动词去"],
    "answer": "取消句子独立性",
    "explanation": "前置宾语标志，取消句子独立性，\"先生之乎\"中\"之\"字无实义",
  },
  {
    "id": "chinese-089",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "抽刀断水水更流，_____。",
    "options": ["借酒浇愁愁更愁", "举杯消愁愁更愁", "明朝散发弄扁舟", "不知明镜里"],
    "answer": "举杯消愁愁更愁",
    "explanation": "出自李白《宣州谢眺楼饯别校书叔云》：抽刀断水水更流，举杯消愁愁更愁",
  },
  {
    "id": "chinese-090",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "下列引号作用不同于其他三项的是：",
    "options": ["人称计算机的书房", "说学逗唱", "这样的瘦肉", "活该"],
    "answer": "说学逗唱",
    "explanation": "说学逗唱是相声基本功，此处引号表示特定称谓；其他表示讽刺或强调",
  },
  {
    "id": "chinese-091",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《水调歌头明月几时有》中，表现作者美好祝愿的句子是：",
    "options": ["我欲乘风归去", "起舞弄清影", "何似在人间", "千里共婵娟"],
    "answer": "千里共婵娟",
    "explanation": "但愿人长久，千里共婵娟，是作者对弟弟的美好祝愿，也是对天下人的祝愿",
  },
  {
    "id": "chinese-092",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词性辨析"],
    "question": "下列词语中，属于名词的是：",
    "options": ["忽然", "突然", "猛然", "突然性"],
    "answer": "突然性",
    "explanation": "忽然、突然、猛然都是副词；突然性是名词",
  },
  {
    "id": "chinese-093",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《愚公移山》属于：",
    "options": ["神话传说", "寓言故事", "历史故事", "民间笑话"],
    "answer": "寓言故事",
    "explanation": "《愚公移山》出自《列子》，是一则寓言故事，通过虚构故事说明道理",
  },
  {
    "id": "chinese-094",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字音"],
    "question": "下列加点字读音完全正确的是：",
    "options": ["折本(se)", "折纸(zhe)", "折断(zhe)", "折腾(zhe)"],
    "answer": "折本(se)",
    "explanation": "折本(se)是赔本的意思，其他都读zhe",
  },
  {
    "id": "chinese-095",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《白雪歌送武判官归京》中，写雪景的名句是：",
    "options": ["北风卷地白草折", "胡天八月即飞雪", "忽如一夜春风来", "纷纷暮雪下辕门"],
    "answer": "忽如一夜春风来",
    "explanation": "忽如一夜春风来，千树万树梨花开，以梨花喻雪，是描写雪景的千古名句",
  },
  {
    "id": "chinese-096",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["病句修改"],
    "question": "下列句子中，表述正确的是：",
    "options": ["我的差不多都完成了。", "我的作业差不多全部完成了。", "我的作业全部差不多了。", "我的作业差不多完全完成了。"],
    "answer": "我的作业差不多全部完成了。",
    "explanation": "差不多和全部语义矛盾；全部差不多了搭配不当；差不多完全也有矛盾",
  },
  {
    "id": "chinese-097",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-句子成分"],
    "question": "下列句子中，谓语是动词的是：",
    "options": ["春天是美丽的。", "他的态度很诚恳。", "我赞成你的意见。", "这个问题很容易。"],
    "answer": "我赞成你的意见。",
    "explanation": "A主系表结构；B主系表结构；D主系表结构；C谓语是动词赞成",
  },
  {
    "id": "chinese-098",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "胜在引人入胜中的意思是：",
    "options": ["胜利", "超过", "优美", "能承受"],
    "answer": "优美",
    "explanation": "引人入胜：吸引人进入优美的境界，胜是优美的意思",
  },
  {
    "id": "chinese-099",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "填写：问君能有几多愁？_____。",
    "answer": "恰似一江春水向东流",
    "explanation": "出自李煜《虞美人》：春花秋月何时了，往事知多少。小楼昨夜又东风，故国不堪回首月明中。雕栏玉砌应犹在，只是朱颜改。问君能有几多愁？恰似一江春水向东流。",
  },
  {
    "id": "chinese-100",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "下列句子使用了反复修辞的是：",
    "options": ["我爱你，祖国！我爱你，祖国！", "他的脸上洋溢着幸福的笑容。", "太阳出来了，像火球。", "小明和小红一起上学。"],
    "answer": "我爱你，祖国！我爱你，祖国！",
    "explanation": "反复是同一词句的重复使用，表示强调和情感强烈；A是反复；B是拟人；C是比喻；D是对偶",
  },
  {
    "id": "chinese-101",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《孟子》是_____及门弟子的著作汇编。",
    "options": ["庄子", "老子", "孟子", "孔子"],
    "answer": "孟子",
    "explanation": "《孟子》是记录孟子言行的著作，由孟子和他的弟子共同编写",
  },
  {
    "id": "chinese-102",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "人有悲欢离合，_____。",
    "options": ["月有阴晴圆缺此事古难全", "但愿人长久千里共婵娟", "我欲乘风归去", "不知天上宫阙"],
    "answer": "月有阴晴圆缺此事古难全",
    "explanation": "出自苏轼《水调歌头》：人有悲欢离合，月有阴晴圆缺，此事古难全",
  },
  {
    "id": "chinese-103",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字形"],
    "question": "下列词语中，含有错别字的是：",
    "options": ["川流不息", "走投无路", "不记其数", "守株待兔"],
    "answer": "不记其数",
    "explanation": "不记其数应为不计其数，计是计算的意思",
  },
  {
    "id": "chinese-104",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-短语结构"],
    "question": "短语结构相同的是：",
    "options": ["改革开放 密切联系", "雄伟壮丽 阴晴圆缺", "努力学习 光辉典范", "我的老师 伟大祖国"],
    "answer": "改革开放 密切联系",
    "explanation": "改革开放是并列结构，密切联系也是并列结构；其他选项结构不全相同",
  },
  {
    "id": "chinese-105",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《茅屋为秋风所破歌》的作者是：",
    "options": ["李白", "杜甫", "白居易", "王维"],
    "answer": "杜甫",
    "explanation": "杜甫在穷困潦倒之际写下此诗，表达忧国忧民的情怀",
  },
  {
    "id": "chinese-106",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["词类活用"],
    "question": "下列句子中没有词类活用的是：",
    "options": ["一狼洞其中。", "京中有善口技者。", "狼不敢前。", "温故而知新。"],
    "answer": "温故而知新。",
    "explanation": "A洞是名词作动词；B善是形容词作动词；C前是名词作动词；D故和新都是名词，无活用",
  },
  {
    "id": "chinese-107",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "沉舟侧畔千帆过，_____。",
    "options": ["病树前头万木春", "两岸猿声啼不住", "轻舟已过万重山", "柳暗花明又一村"],
    "answer": "病树前头万木春",
    "explanation": "出自刘禹锡《酬乐天扬州初逢席上见赠》，比喻旧事物必将消亡，新事物必将成长",
  },
  {
    "id": "chinese-108",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["修辞手法"],
    "question": "下列句子中不是比喻的是：",
    "options": ["天街小雨润如酥。", "桃花潭水深千尺。", "她像他妈妈。", "影子拖着长长的尾巴。"],
    "answer": "她像他妈妈。",
    "explanation": "A酥是春雨，比喻；B千尺是夸张；C是判断句，不是比喻",
  },
  {
    "id": "chinese-109",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "下列作品不属于鲁迅的是：",
    "options": ["《从百草园到三味书屋》", "《藤野先生》", "《背影》", "《孔乙己》"],
    "answer": "背影",
    "explanation": "《背影》是朱自清的作品；其他都是鲁迅的散文",
  },
  {
    "id": "chinese-110",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-复句类型"],
    "question": "既然黑夜给了我黑色的眼睛，_____用它寻找光明。",
    "options": ["我就", "我将", "我却", "我必"],
    "answer": "我就",
    "explanation": "既然...就...是因果复句的典型格式，就表示结果",
  },
  {
    "id": "chinese-111",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["字音"],
    "question": "下列词语中，加点字读音正确的是：",
    "options": ["气氛(fen) 玫瑰(gui)", "气氛(fen) 玫瑰(gui)", "分外(fen) 分歧(zhi)", "分析(xi) 分娩(fen)"],
    "answer": "气氛(fen) 玫瑰(gui)",
    "explanation": "分(fen)外，但分(fen)歧中分读fen；分析fen，分娩fen",
  },
  {
    "id": "chinese-112",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《酬乐天扬州初逢席上见赠》中，怀旧之情的句子是：",
    "options": ["沉舟侧畔千帆过", "病树前头万木春", "二十三年弃置身", "暂凭杯酒长精神"],
    "answer": "二十三年弃置身",
    "explanation": "怀旧：二十三年弃置身，旧时朋友多已离世，物是人非之感",
  },
  {
    "id": "chinese-113",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["古诗文默写"],
    "question": "山回路转不见君，_____。",
    "options": ["雪上空留马行处", "柳暗花明又一村", "草色遥看近却无", "花重锦官城"],
    "answer": "雪上空留马行处",
    "explanation": "出自岑参《白雪歌送武判官归京》，表达了诗人送别友人后的惆怅",
  },
  {
    "id": "chinese-114",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["词义辨析"],
    "question": "谢在代谢中的意思是：",
    "options": ["感谢", "凋落", "衰退", "道歉"],
    "answer": "凋落",
    "explanation": "代谢：新陈代谢，指事物更新替换，谢是凋落、衰退的意思",
  },
  {
    "id": "chinese-115",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["文学常识"],
    "question": "《诗经》按照_____分为风、雅、颂三部分。",
    "options": ["音乐性质", "地域", "内容", "形式"],
    "answer": "音乐性质",
    "explanation": "《诗经》根据音乐性质分为三部分：风是各国民歌，雅是宫廷乐歌，颂是宗庙祭祀乐歌",
  },
  {
    "id": "chinese-116",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["病句修改"],
    "question": "通过这次活动，使我提高了认识。",
    "options": ["去掉通过", "去掉使", "去掉这次活动", "去掉这次活动或通过"],
    "answer": "去掉通过或去掉使",
    "explanation": "缺主语，去掉通过或使即可，主语是这次活动使我们提高",
  },
  {
    "id": "chinese-117",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["词性辨析"],
    "question": "突然和忽然的关系是：",
    "options": ["同义词", "古今关系", "口语与书面语", "以上都是"],
    "answer": "以上都是",
    "explanation": "突然和忽然后古代是同义词，现在都是副词，是古今同义关系，口语书面语都可用",
  },
  {
    "id": "chinese-118",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["古诗文理解"],
    "question": "《登飞来峰》中，不畏浮云遮望眼的原因是：",
    "options": ["我很高", "身在最高层", "浮云太多", "我不怕"],
    "answer": "身在最高层",
    "explanation": "不畏浮云遮望眼，只缘身在最高层，站得高才能看得远",
  },
  {
    "id": "chinese-119",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["标点符号"],
    "question": "下列句子中引号不属于直接引用的是：",
    "options": ["老师说：要多读书。", "古人说：一寸光阴一寸金。", "他是一个所谓的好学生。", "我最喜欢读《十万个为什么》。"],
    "answer": "他是一个所谓的好学生。",
    "explanation": "C所谓表示讽刺否定，不是直接引用；A、B是直接引语；D书名号不是引号",
  },
  {
    "id": "chinese-120",
    "type": "choice",
    "subject": "chinese",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["语法-短语类型"],
    "question": "短语类型不同的是：",
    "options": ["慢慢走", "悄悄说", "哈哈大笑", "认认真真学习"],
    "answer": "认认真真学习",
    "explanation": "A、B、C是状语+动词；D是重叠形容词+动词，且多了状语",
  },
];