// GEOGRAPHY — 20 questions, auto-generated from batch_*.json
// Last updated: 2026-04-13

export default [
  {
    "id": "geography-021",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-地形"],
    "question": "我国最大的平原是：",
    "options": ["华北平原", "东北平原", "长江中下游平原", "成都平原"],
    "answer": "东北平原",
    "explanation": "东北平原是我国面积最大的平原，约35万平方公里，包括三江平原、松嫩平原、辽河平原",
  },
  {
    "id": "geography-022",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["世界地理-气候"],
    "question": "热带雨林气候主要分布在：",
    "options": ["赤道附近", "回归线附近", "极圈附近", "温带内陆"],
    "answer": "赤道附近",
    "explanation": "热带雨林气候主要分布在赤道附近，如亚马逊平原、刚果盆地、东南亚群岛",
  },
  {
    "id": "geography-023",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-行政区划"],
    "question": "我国少数民族数量最多的省级行政区是：",
    "options": ["新疆维吾尔自治区", "广西壮族自治区", "云南省", "贵州省"],
    "answer": "云南省",
    "explanation": "云南省有25个少数民族，是我国少数民族数量最多的省份",
  },
  {
    "id": "geography-024",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "世界上面积最大的湖泊是：",
    "options": ["贝加尔湖", "里海", "死海", "青海湖"],
    "answer": "里海",
    "explanation": "里海是世界上面积最大的湖泊，同时也是世界上面积最大的咸水湖，位于亚欧交界处",
  },
  {
    "id": "geography-025",
    "type": "fill",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-河流"],
    "question": "长江和黄河都发源于青海省的_____高原。",
    "answer": "青藏",
    "explanation": "长江发源于唐古拉山，黄河发源于巴颜喀拉山，都位于青藏高原",
  },
  {
    "id": "geography-026",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["世界地理-人口"],
    "question": "世界上人口最多的大洲是：",
    "options": ["亚洲", "非洲", "欧洲", "北美洲"],
    "answer": "亚洲",
    "explanation": "亚洲是世界上人口最多的大洲，约47亿人，占世界总人口约60%",
  },
  {
    "id": "geography-027",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["中国地理-资源"],
    "question": "我国土地资源的特点是：",
    "options": ["总量多，人均少", "总量少，人均多", "总量多，人均多", "总量少，人均少"],
    "answer": "总量多，人均少",
    "explanation": "我国土地资源总量居世界前列，但人均占有量远低于世界平均水平",
  },
  {
    "id": "geography-028",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "世界上最高的高原是：",
    "options": ["巴西高原", "青藏高原", "东非高原", "德干高原"],
    "answer": "青藏高原",
    "explanation": "青藏高原平均海拔4000米以上，被称为世界屋脊，是世界上最高的高原",
  },
  {
    "id": "geography-029",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["中国地理-气候"],
    "question": "我国季风气候的特点是：",
    "options": ["夏季温和少雨，冬季寒冷多雨", "夏季高温多雨，冬季寒冷干燥", "全年温和湿润", "全年炎热干燥"],
    "answer": "夏季高温多雨，冬季寒冷干燥",
    "explanation": "我国大部分地区属于季风气候，夏季受来自太平洋的东南季风影响，高温多雨；冬季受来自内陆的西北季风影响，寒冷干燥",
  },
  {
    "id": "geography-030",
    "type": "fill",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "世界上最长的河流是非洲的_____河。",
    "answer": "尼罗",
    "explanation": "尼罗河全长约6670公里，是世界上最长的河流，主要流经埃及、苏丹等国家",
  },
  {
    "id": "geography-031",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-行政区划"],
    "question": "我国面积最大的省级行政区是：",
    "options": ["内蒙古自治区", "新疆维吾尔自治区", "西藏自治区", "四川省"],
    "answer": "新疆维吾尔自治区",
    "explanation": "新疆维吾尔自治区面积约166万平方公里，是我国面积最大的省级行政区",
  },
  {
    "id": "geography-032",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["世界地理-经济"],
    "question": "发达国家主要分布在：",
    "options": ["亚洲、非洲、拉丁美洲", "北美洲、欧洲、大洋洲", "南美洲、非洲、大洋洲", "亚洲、欧洲、南美洲"],
    "answer": "北美洲、欧洲、大洋洲",
    "explanation": "发达国家主要集中在北美洲（如美国、加拿大）、欧洲（如英、法、德）和大洋洲（如澳大利亚、新西兰）",
  },
  {
    "id": "geography-033",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "世界上海拔最高的山峰是：",
    "options": ["乞力马扎罗山", "乔戈里峰", "珠穆朗玛峰", "干城章嘉峰"],
    "answer": "珠穆朗玛峰",
    "explanation": "珠穆朗玛峰海拔8848.86米，是世界最高峰，位于中国与尼泊尔边境",
  },
  {
    "id": "geography-034",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["中国地理-交通"],
    "question": "我国最重要的铁路干线京广线的起止点是：",
    "options": ["北京-广州", "北京-上海", "上海-广州", "南京-北京"],
    "answer": "北京-广州",
    "explanation": "京广线北起北京，南至广州，全长约2300公里，是我国最重要的南北铁路干线",
  },
  {
    "id": "geography-035",
    "type": "fill",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "世界面积最大的大洲是_____洲。",
    "answer": "亚",
    "explanation": "亚洲面积约4458万平方公里，是世界面积最大的大洲",
  },
  {
    "id": "geography-036",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-气候"],
    "question": "我国年降水量分布的总趋势是：",
    "options": ["从东南向西北递减", "从西北向东南递减", "从北向南递减", "从南向北递减"],
    "answer": "从东南向西北递减",
    "explanation": "受夏季风影响，我国年降水量从东南向西北递减，东南沿海地区降水多，西北内陆地区降水少",
  },
  {
    "id": "geography-037",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "撒哈拉沙漠位于：",
    "options": ["亚洲", "非洲", "澳大利亚", "南美洲"],
    "answer": "非洲",
    "explanation": "撒哈拉沙漠位于非洲北部，是世界上面积最大的沙漠，约920万平方公里",
  },
  {
    "id": "geography-038",
    "type": "choice",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-行政区划"],
    "question": "我国纬度最高的省级行政区是：",
    "options": ["黑龙江省", "吉林省", "内蒙古自治区", "新疆维吾尔自治区"],
    "answer": "黑龙江省",
    "explanation": "黑龙江省位于我国最东北部，是我国纬度最高的省份，漠河镇有北极村之称",
  },
  {
    "id": "geography-039",
    "type": "choice",
    "subject": "geography",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["世界地理-自然环境"],
    "question": "澳大利亚大陆主要位于哪个温度带？",
    "options": ["热带", "南温带", "北温带", "寒带"],
    "answer": "南温带",
    "explanation": "澳大利亚大陆约三分之二位于南回归线以南，主要属于南温带",
  },
  {
    "id": "geography-040",
    "type": "fill",
    "subject": "geography",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["中国地理-地形"],
    "question": "我国地势的特点是西高东低，呈_____级阶梯状分布。",
    "answer": "三",
    "explanation": "我国地势呈三级阶梯状分布：青藏高原为第一级阶梯，海拔4000米以上；黄土高原、云贵高原等为第二级阶梯；东北平原、华北平原等为第三级阶梯",
  },
];