// MATH — 72 questions, auto-generated from batch_*.json
// Last updated: 2026-04-13

export default [
  {
    "id": "math-079",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "在三角形ABC中，角A=90度，角B=45度，则角C=_____",
    "options": ["45度", "90度", "135度", "30度"],
    "answer": "45度",
    "explanation": "三角形内角和180度，180-90-45=45度",
  },
  {
    "id": "math-080",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["平面直角坐标系"],
    "question": "已知点A(2,3)，B(-1,3)，则AB的长度为_____",
    "options": ["1", "2", "3", "6"],
    "answer": "3",
    "explanation": "AB = |2-(-1)| = 3，横坐标差为3，纵坐标相同",
  },
  {
    "id": "math-081",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：(-a)的三次方 = _____",
    "options": ["-a³", "a³", "-a", "a"],
    "answer": "-a³",
    "explanation": "(-a)³ = (-1)³·a³ = -a³",
  },
  {
    "id": "math-082",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["不等式"],
    "question": "不等式组 x>3 和 x<7 的解集是_____",
    "options": ["3<x<7", "x>3", "x<7", "无解"],
    "answer": "3<x<7",
    "explanation": "两个不等式同时成立，取交集得 3<x<7",
  },
  {
    "id": "math-083",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "计算：2³ = _____",
    "options": ["6", "8", "9", "16"],
    "answer": "8",
    "explanation": "2³ = 2×2×2 = 8",
  },
  {
    "id": "math-084",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：x² - 4x + 4 = _____",
    "options": ["(x-2)²", "(x+2)²", "(x-4)(x+1)", "(x+1)(x-4)"],
    "answer": "(x-2)²",
    "explanation": "完全平方公式：a²-2ab+b²=(a-b)²，这里x²-4x+4=(x-2)²",
  },
  {
    "id": "math-085",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "9的平方根是_____",
    "options": ["3", "-3", "±3", "81"],
    "answer": "±3",
    "explanation": "平方根是指正负两个，√9=3，所以平方根是±3",
  },
  {
    "id": "math-086",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["二元一次方程组"],
    "question": "解方程组 x+2y=7, 2x-y=4，x=_____",
    "options": ["1", "2", "3", "4"],
    "answer": "3",
    "explanation": "由第一个方程x=7-2y，代入第二个：2(7-2y)-y=4→14-4y-y=4→-5y=-10→y=2→x=3",
  },
  {
    "id": "math-087",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "等边三角形每个角是_____度",
    "options": ["30", "45", "60", "90"],
    "answer": "60",
    "explanation": "等边三角形三个角相等，180÷3=60度",
  },
  {
    "id": "math-088",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["分式"],
    "question": "当 x=_____ 时，分式 (x-3)/(x+1) 的值为零",
    "options": ["3", "-3", "1", "-1"],
    "answer": "3",
    "explanation": "分式为零的条件：分子=0且分母≠0，x-3=0得x=3，代入分母3+1=4≠0，所以x=3",
  },
  {
    "id": "math-089",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：5a - 3a = _____",
    "options": ["2", "2a", "8a", "15a"],
    "answer": "2a",
    "explanation": "合并同类项，系数相减：5-3=2",
  },
  {
    "id": "math-090",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一次函数"],
    "question": "函数 y = -3x + 2，y随x的增大而_____",
    "options": ["增大", "减小", "不变", "先增后减"],
    "answer": "减小",
    "explanation": "k=-3<0，所以y随x增大而减小",
  },
  {
    "id": "math-091",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "任何不等于零的数的零次幂等于_____",
    "options": ["0", "1", "该数本身", "无穷大"],
    "answer": "1",
    "explanation": "a⁰ = 1（a≠0），这是零指数幂的规定",
  },
  {
    "id": "math-092",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一元一次方程"],
    "question": "方程 4x + 3 = 2x + 9 的解是 x=_____",
    "options": ["1", "2", "3", "4"],
    "answer": "3",
    "explanation": "4x-2x=9-3，2x=6，x=3",
  },
  {
    "id": "math-093",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["平面直角坐标系"],
    "question": "点(0,5)在_____轴上",
    "options": ["x", "y", "原点", "无法确定"],
    "answer": "y",
    "explanation": "x=0时点在y轴上",
  },
  {
    "id": "math-094",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "三角形的两边长分别为3和5，则第三边a的取值范围是_____",
    "options": ["2<a<8", "2<a<5", "3<a<8", "a>2"],
    "answer": "2<a<8",
    "explanation": "三角形两边之和大于第三边，两边之差小于第三边：5-3<a<5+3，即2<a<8",
  },
  {
    "id": "math-095",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "最小的正整数是_____",
    "options": ["0", "1", "-1", "不存在"],
    "answer": "1",
    "explanation": "正整数是大于0的整数，最小的是1；0不是正数也不是负数",
  },
  {
    "id": "math-096",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：3x² - 12 = _____",
    "options": ["3(x-2)²", "3(x+2)(x-2)", "(3x-6)(x+2)", "3x(x-4)"],
    "answer": "3(x+2)(x-2)",
    "explanation": "先提公因式3：3(x²-4)，再用平方差公式x²-4=(x+2)(x-2)",
  },
  {
    "id": "math-097",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "计算：10³ = _____",
    "options": ["30", "100", "1000", "10000"],
    "answer": "1000",
    "explanation": "10³ = 10×10×10 = 1000",
  },
  {
    "id": "math-098",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["二元一次方程组"],
    "question": "若x+y=5，且x-y=1，则x和y分别为_____",
    "options": ["3和2", "2和3", "4和1", "5和0"],
    "answer": "3和2",
    "explanation": "相加：2x=6→x=3，相减：2y=4→y=2",
  },
  {
    "id": "math-099",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "单项式 -3x²y 的系数是_____",
    "options": ["-3", "3", "-2", "2"],
    "answer": "-3",
    "explanation": "单项式中的数字因数叫系数，-3x²y的系数是-3",
  },
  {
    "id": "math-100",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["不等式"],
    "question": "不等式 -x > 3 的解集是_____",
    "options": ["x > -3", "x < -3", "x > 3", "x < 3"],
    "answer": "x < -3",
    "explanation": "两边除以-1（负数变号）：x < -3",
  },
  {
    "id": "math-101",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "(-2)的二次方 = _____",
    "options": ["4", "-4", "2", "-2"],
    "answer": "4",
    "explanation": "(-2)² = (-2)×(-2) = 4，负负得正",
  },
  {
    "id": "math-102",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一次函数"],
    "question": "正比例函数 y = kx，当 x=2 时 y=6，则 k=_____",
    "options": ["2", "3", "4", "12"],
    "answer": "3",
    "explanation": "6 = k×2，k = 3",
  },
  {
    "id": "math-103",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "三角形的外角一定_____内角",
    "options": ["大于", "小于", "等于", "无法确定"],
    "answer": "大于",
    "explanation": "三角形的一个外角大于任何一个与它不相邻的内角",
  },
  {
    "id": "math-104",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：(x+1)(x-1) = _____",
    "options": ["x²-1", "x²+1", "x²-2x+1", "x²+2x+1"],
    "answer": "x²-1",
    "explanation": "平方差公式：(x+1)(x-1) = x²-1",
  },
  {
    "id": "math-105",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "下列是无理数的是_____",
    "options": ["√9", "π", "0.5", "1/3"],
    "answer": "π",
    "explanation": "π是无限不循环小数，是无理数；√9=3是有理数",
  },
  {
    "id": "math-106",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["分式"],
    "question": "分式 (x²-4)/(x-2) 化简结果是_____",
    "options": ["x-2", "x+2", "x²-2", "x²+2"],
    "answer": "x+2",
    "explanation": "x²-4=(x+2)(x-2)，约去(x-2)得x+2",
  },
  {
    "id": "math-107",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "a⁴ ÷ a² = _____",
    "options": ["a²", "a⁶", "a⁸", "1"],
    "answer": "a²",
    "explanation": "同底数幂相除，指数相减：a⁴⁻² = a²",
  },
  {
    "id": "math-108",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["平面直角坐标系"],
    "question": "点P(-3,4)到原点的距离是_____",
    "options": ["5", "7", "1", "25"],
    "answer": "5",
    "explanation": "距离 = √((-3)²+4²) = √(9+16) = √25 = 5",
  },
  {
    "id": "math-109",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "多项式 4x² - 3x + 1 是_____次_____项式",
    "options": ["二，三", "二，二", "一，三", "三，四"],
    "answer": "二，三",
    "explanation": "最高次数是2次，有三项，是二次三项式",
  },
  {
    "id": "math-110",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一元一次方程"],
    "question": "方程 5 - 2x = 1 的解是 x=_____",
    "options": ["1", "2", "3", "-2"],
    "answer": "2",
    "explanation": "-2x = 1-5 = -4，x = 2",
  },
  {
    "id": "math-111",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "直角三角形的两锐角和是_____度",
    "options": ["90", "180", "360", "45"],
    "answer": "90",
    "explanation": "直角三角形内角和180度，直角90度，两锐角和为90度",
  },
  {
    "id": "math-112",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：x² + 6x + 9 = _____",
    "options": ["(x+3)²", "(x-3)²", "(x+9)(x+1)", "(x-9)(x+1)"],
    "answer": "(x+3)²",
    "explanation": "完全平方公式：x²+2·x·3+3²=(x+3)²",
  },
  {
    "id": "math-113",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "(-1)的2026次方 = _____",
    "options": ["1", "-1", "0", "2026"],
    "answer": "1",
    "explanation": "偶数次幂，(-1)²⁰²⁶ = 1",
  },
  {
    "id": "math-114",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一次函数"],
    "question": "一次函数 y = 5x - 3 与x轴的交点是_____",
    "options": ["(0,-3)", "(3/5,0)", "(0,3/5)", "(-3,0)"],
    "answer": "(3/5,0)",
    "explanation": "与x轴相交时y=0，0=5x-3，x=3/5，所以交点是(3/5,0)",
  },
  {
    "id": "math-115",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "数轴上的点与_____一一对应",
    "options": ["整数", "有理数", "实数", "自然数"],
    "answer": "实数",
    "explanation": "数轴上的每个点唯一对应一个实数，实数与数轴上的点一一对应",
  },
  {
    "id": "math-116",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["二元一次方程组"],
    "question": "方程组 x+2y=6, x-2y=2 的解是_____",
    "options": ["x=4,y=1", "x=2,y=2", "x=3,y=1.5", "x=1,y=4"],
    "answer": "x=4,y=1",
    "explanation": "相加：2x=8→x=4，代入：4+2y=6→2y=2→y=1",
  },
  {
    "id": "math-117",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "2的负一次方 = _____",
    "options": ["-2", "-1/2", "1/2", "2"],
    "answer": "1/2",
    "explanation": "2⁻¹ = 1/2¹ = 1/2",
  },
  {
    "id": "math-118",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "在△ABC中，AB=AC，若角A=40度，则角B=_____度",
    "options": ["40", "70", "140", "50"],
    "answer": "70",
    "explanation": "等腰三角形，角B=角C=(180-40)/2=70度",
  },
  {
    "id": "math-119",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：(a³)² = _____",
    "options": ["a⁵", "a⁶", "a⁹", "2a³"],
    "answer": "a⁶",
    "explanation": "幂的乘方，指数相乘：(a³)² = a³˟² = a⁶",
  },
  {
    "id": "math-120",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["不等式"],
    "question": "不等式 3x - 1 ≤ 5 的解集是_____",
    "options": ["x ≤ 2", "x ≥ 2", "x ≤ -2", "x ≥ -2"],
    "answer": "x ≤ 2",
    "explanation": "3x ≤ 6，x ≤ 2",
  },
  {
    "id": "math-121",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "三角形的三条高交于一点，这一点叫三角形的_____",
    "options": ["重心", "垂心", "内心", "外心"],
    "answer": "垂心",
    "explanation": "三角形三条高的交点叫垂心；重心是三条中线的交点；内心是三条角平分线的交点；外心是三条垂直平分线的交点",
  },
  {
    "id": "math-122",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["分式"],
    "question": "分式方程 1/x = 1/3 的解是_____",
    "options": ["x=3", "x=1/3", "x=0", "无解"],
    "answer": "x=3",
    "explanation": "两边倒数：x=3，注意x不能为0",
  },
  {
    "id": "math-123",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "若 a² = 16，则 a = _____",
    "options": ["4", "-4", "±4", "8"],
    "answer": "±4",
    "explanation": "平方根有两个，a = ±4",
  },
  {
    "id": "math-124",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：m² - n² = _____",
    "options": ["(m-n)²", "(m+n)²", "(m-n)(m+n)", "(m+n)(m-n)"],
    "answer": "(m-n)(m+n)",
    "explanation": "平方差公式：a²-b²=(a-b)(a+b)",
  },
  {
    "id": "math-125",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：-5 + 3 = _____",
    "options": ["-8", "-2", "2", "8"],
    "answer": "-2",
    "explanation": "-5+3=-2",
  },
  {
    "id": "math-126",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["二元一次方程组"],
    "question": "方程组 3x+y=10, x-y=2 的解中 x+y=_____",
    "options": ["4", "6", "8", "10"],
    "answer": "6",
    "explanation": "相加：4x=12→x=3，代入：3-y=2→y=1，所以x+y=4",
  },
  {
    "id": "math-127",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["平面直角坐标系"],
    "question": "若点P在第四象限，则点P的坐标特点是_____",
    "options": ["x>0,y>0", "x>0,y<0", "x<0,y>0", "x<0,y<0"],
    "answer": "x>0,y<0",
    "explanation": "第四象限：x>0（正），y<0（负）",
  },
  {
    "id": "math-128",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["不等式"],
    "question": "不等式 x-3 > 2 的解集在数轴上表示正确的是_____",
    "options": ["x>5", "x<5", "x>1", "x<1"],
    "answer": "x>5",
    "explanation": "x-3>2，x>5",
  },
  {
    "id": "math-129",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "三角形具有_____性",
    "options": ["稳定", "灵活", "对称", "以上都不是"],
    "answer": "稳定",
    "explanation": "三角形具有稳定性，四边形具有不稳定性",
  },
  {
    "id": "math-130",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一次函数"],
    "question": "函数 y = -2x + 4，当 x 增大时，y _____",
    "options": ["增大", "减小", "不变", "先增后减"],
    "answer": "减小",
    "explanation": "k=-2<0，y随x增大而减小",
  },
  {
    "id": "math-131",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "计算：(-3)² = _____",
    "options": ["9", "-9", "6", "-6"],
    "answer": "9",
    "explanation": "(-3)² = 9，负数平方得正",
  },
  {
    "id": "math-132",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：(x-y)² - 4 = _____",
    "options": ["(x-y-2)(x-y+2)", "(x-y-2)²", "(x+y-2)(x-y+2)", "(x-y+2)²"],
    "answer": "(x-y-2)(x-y+2)",
    "explanation": "平方差：a²-b²=(a-b)(a+b)，这里a=(x-y)，b=2",
  },
  {
    "id": "math-133",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "去括号：-(a-b) = _____",
    "options": ["-a-b", "-a+b", "a-b", "a+b"],
    "answer": "-a+b",
    "explanation": "-(a-b) = -a+(-b) = -a+b，或直接：负号分配",
  },
  {
    "id": "math-134",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "下列说法正确的是：",
    "options": ["有限小数是有理数", "无限不循环小数是有理数", "带根号的数都是无理数", "所有分数都是有理数"],
    "answer": "有限小数是有理数",
    "explanation": "有限小数和无限循环小数都是有理数；无限不循环小数是无理数；√4=2是有理数",
  },
  {
    "id": "math-135",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "一个三角形的三个内角度数比为1:2:3，则最大角是_____度",
    "options": ["30", "60", "90", "45"],
    "answer": "90",
    "explanation": "设三角分别为x,2x,3x，x+2x+3x=180，6x=180，x=30，最大角3x=90度",
  },
  {
    "id": "math-136",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["分式"],
    "question": "化简：(x²+2x+1)/(x+1) = _____",
    "options": ["x+1", "x²+2", "x-1", "x²-1"],
    "answer": "x+1",
    "explanation": "分子=(x+1)²，约去(x+1)得x+1",
  },
  {
    "id": "math-137",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "计算：0.1¹ = _____",
    "options": ["0.1", "1", "10", "0.01"],
    "answer": "0.1",
    "explanation": "0.1¹ = 0.1",
  },
  {
    "id": "math-138",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一元一次方程"],
    "question": "方程 7x + 2 = 3x + 18 的解是 x=_____",
    "options": ["2", "3", "4", "5"],
    "answer": "4",
    "explanation": "7x-3x=18-2，4x=16，x=4",
  },
  {
    "id": "math-139",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：(-7) + 4 = _____",
    "options": ["-11", "-3", "3", "11"],
    "answer": "-3",
    "explanation": "-7+4=-3",
  },
  {
    "id": "math-140",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["二元一次方程组"],
    "question": "用代入法解方程组 y=2x, x+y=9，x=_____",
    "options": ["2", "3", "4", "5"],
    "answer": "3",
    "explanation": "代入：x+2x=9，3x=9，x=3",
  },
  {
    "id": "math-141",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "等腰三角形的顶角是50度，底角是_____度",
    "options": ["50", "65", "130", "40"],
    "answer": "65",
    "explanation": "底角=(180-50)/2=65度",
  },
  {
    "id": "math-142",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["一次函数"],
    "question": "一次函数 y = kx + b，k>0且b<0，图像经过第_____象限",
    "options": ["一、二", "一、三", "二、三、四", "一、三、四"],
    "answer": "一、三、四",
    "explanation": "k>0过一三象限，b<0过四象限，综合过一、三、四象限",
  },
  {
    "id": "math-143",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "若 a³ = 27，则 a = _____",
    "options": ["3", "9", "27", "±3"],
    "answer": "3",
    "explanation": "a³=27，a=3",
  },
  {
    "id": "math-144",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["不等式"],
    "question": "不等式组 2x<6, x+1>2 的解集是_____",
    "options": ["x<3", "x>1", "1<x<3", "x>3"],
    "answer": "1<x<3",
    "explanation": "2x<6→x<3，x+1>2→x>1，取交集1<x<3",
  },
  {
    "id": "math-145",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["平面直角坐标系"],
    "question": "点(2,-3)在第_____象限",
    "options": ["一", "二", "三", "四"],
    "answer": "四",
    "explanation": "第四象限：x>0，y<0",
  },
  {
    "id": "math-146",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["因式分解"],
    "question": "因式分解：5x²y - 10xy² = _____",
    "options": ["5xy(x-y)", "5xy(x-2y)", "5x²(y-2y)", "5xy(x+y)"],
    "answer": "5xy(x-2y)",
    "explanation": "提公因式5xy：5xy(x-2y)",
  },
  {
    "id": "math-147",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["整式运算"],
    "question": "计算：-2 × (-3) = _____",
    "options": ["-6", "6", "-5", "5"],
    "answer": "6",
    "explanation": "负负得正，-2×(-3)=6",
  },
  {
    "id": "math-148",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["实数"],
    "question": "√2 约等于_____（保留两位小数）",
    "options": ["1.41", "1.73", "2.24", "1.50"],
    "answer": "1.41",
    "explanation": "√2≈1.41421356，保留两位小数1.41",
  },
  {
    "id": "math-149",
    "type": "choice",
    "subject": "math",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["幂的运算"],
    "question": "计算：2³ × 2⁴ = _____",
    "options": ["2⁷", "2¹²", "4⁷", "2⁷或128"],
    "answer": "2⁷",
    "explanation": "同底数幂相乘，指数相加：2³⁺⁴=2⁷=128",
  },
  {
    "id": "math-150",
    "type": "choice",
    "subject": "math",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["三角形"],
    "question": "已知等腰三角形一边为4，另一边为9，周长是_____",
    "options": ["17", "22", "13", "17或22"],
    "answer": "22",
    "explanation": "等腰三角形两腰相等，4+9+9=22（4+4=8<9不成立）；9+9+4=22（9+4>9成立）",
  },
];