// POLITICS — 20 questions, auto-generated from batch_*.json
// Last updated: 2026-04-13

export default [
  {
    "id": "politics-021",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["心理品质"],
    "question": "一个人具有良好的心理品质，有助于：",
    "options": ["只对学习有帮助", "只对交往有帮助", "身心健康成长，更好地适应社会", "只对工作有帮助"],
    "answer": "身心健康成长，更好地适应社会",
    "explanation": "良好的心理品质对一个人的全面发展具有重要意义，有助于身心健康成长，更好地适应社会",
  },
  {
    "id": "politics-022",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["挫折认识"],
    "question": "对挫折的理解正确的是：",
    "options": ["挫折只会给人带来痛苦", "挫折是人生的一部分", "挫折是可以完全避免的", "经历过挫折的人都会成功"],
    "answer": "挫折是人生的一部分",
    "explanation": "挫折是人生的一部分，没有人能一帆风顺，挫折既有消极作用也有积极作用",
  },
  {
    "id": "politics-023",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["情绪调节"],
    "question": "情绪低落时，正确的调节方法是：",
    "options": ["借酒消愁", "大发脾气", "转移注意力", "压抑自己"],
    "answer": "转移注意力",
    "explanation": "转移注意力是调节情绪的好方法，如听音乐、运动、看书等；借酒消愁伤害身体，大发脾气影响人际关系",
  },
  {
    "id": "politics-024",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["情绪调节"],
    "question": "情绪的成分不包括：",
    "options": ["内在体验", "外在表现", "意志水平", "生理唤醒"],
    "answer": "意志水平",
    "explanation": "情绪的成分包括：内在体验（感受）、外在表现（表情）、生理唤醒（生理变化）",
  },
  {
    "id": "politics-025",
    "type": "fill",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["自尊自信"],
    "question": "自尊是既不向别人卑躬屈膝，也不允许别人歧视、侮辱的_____。",
    "answer": "思想品质",
    "explanation": "自尊是一种自己尊重自己、爱护自己，并期望受到他人、集体和社会尊重的内心体验，是一种积极的心理品质",
  },
  {
    "id": "politics-026",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["法律意识"],
    "question": "未成年人的不良行为包括：",
    "options": ["上课认真听讲", "旷课、夜不归宿", "按时完成作业", "遵守校纪校规"],
    "answer": "旷课、夜不归宿",
    "explanation": "旷课、夜不归宿属于未成年人的不良行为；按时完成作业、遵守校纪校规是良好行为",
  },
  {
    "id": "politics-027",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["法律意识"],
    "question": "保护未成年人合法权益的专门法律是：",
    "options": ["《宪法》", "《未成年人保护法》", "《义务教育法》", "《婚姻法》"],
    "answer": "《未成年人保护法》",
    "explanation": "《未成年人保护法》是专门保护未成年人合法权益的法律，分为家庭保护、学校保护、社会保护、司法保护四部分",
  },
  {
    "id": "politics-028",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["个人与集体"],
    "question": "个人与集体的关系是：",
    "options": ["个人利益高于集体利益", "集体利益和个人利益同等重要", "个人离开集体就无法生存", "集体离开个人也能存在"],
    "answer": "集体利益和个人利益同等重要",
    "explanation": "个人与集体相互依存，集体利益和个人利益都很重要，应该把集体利益放在首位，但也尊重个人正当利益",
  },
  {
    "id": "politics-029",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["行为与后果"],
    "question": "行为与后果的关系是：",
    "options": ["行为与后果没有必然联系", "一种行为只会产生一种后果", "行为必然产生后果，有行为必有后果", "有些行为有后果，有些行为没有后果"],
    "answer": "行为必然产生后果，有行为必有后果",
    "explanation": "行为与后果具有一致性，有行为就必然产生后果，行为不同后果也不同",
  },
  {
    "id": "politics-030",
    "type": "fill",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["公民权利"],
    "question": "我国宪法规定，公民有言论、出版、集会、结社、游行、示威的_____。",
    "answer": "自由权利",
    "explanation": "这是我国公民享有的政治自由权利，是公民参与国家政治生活的基础",
  },
  {
    "id": "politics-031",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["心理健康"],
    "question": "关于情绪的描述，不正确的是：",
    "options": ["情绪是复杂的", "情绪是可以调控的", "情绪对青少年没有影响", "情绪可以分为喜、怒、哀、惧等"],
    "answer": "情绪对青少年没有影响",
    "explanation": "情绪对人的身心健康、行为、人际关系等都有重要影响，因此需要学会调节情绪",
  },
  {
    "id": "politics-032",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["责任意识"],
    "question": "做负责任的人，应该做到：",
    "options": ["逃避责任", "减少责任", "信守承诺勇担过错", "只承担他人责任"],
    "answer": "信守承诺勇担过错",
    "explanation": "做负责任的人要：信守承诺，勇担过错，勇担责任，主动承担责任，不推卸责任",
  },
  {
    "id": "politics-033",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["道德教育"],
    "question": "诚实守信是：",
    "options": ["中华民族的最高道德理想", "中华民族的传统美德", "做人的基本要求", "以上都是"],
    "answer": "以上都是",
    "explanation": "诚实守信是中华民族的传统美德，是做人的基本要求，是中华民族的最高道德理想之一",
  },
  {
    "id": "politics-034",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["法律意识"],
    "question": "一般违法行为与犯罪的区别是：",
    "options": ["社会危害性大小不同", "都要受到法律制裁", "违反的都是法律", "都是危害社会的行为"],
    "answer": "社会危害性大小不同",
    "explanation": "一般违法行为和犯罪都违反法律，但社会危害性大小不同，犯罪是严重违法行为",
  },
  {
    "id": "politics-035",
    "type": "fill",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["挫折应对"],
    "question": "面对挫折时，我们要学会一些应对方法，如请求帮助、_____和自我疏导等。",
    "answer": "自我疏导",
    "explanation": "应对挫折的方法包括：请求帮助、自我疏导（写日记、倾诉）、心理安慰、目标调整等",
  },
  {
    "id": "politics-036",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["网络道德"],
    "question": "青少年正确使用网络应该：",
    "options": ["随意浏览不良信息", "遵守道德和法律，不恶意制造和传播信息", "匿名攻击他人", "沉溺于网络游戏"],
    "answer": "遵守道德和法律，不恶意制造和传播信息",
    "explanation": "青少年使用网络要遵守《青少年网络文明公约》，文明上网，遵守道德和法律",
  },
  {
    "id": "politics-037",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["自尊自信"],
    "question": "自卑与自负的共同点是：",
    "options": ["都是正确的自我评价", "都不能客观地看待自己", "都是对自己不利的", "都是对自己有利的"],
    "answer": "都不能客观地看待自己",
    "explanation": "自卑与自负都是不能正确认识自己的表现，自卑低估自己，自负高估自己，都是不客观的",
  },
  {
    "id": "politics-038",
    "type": "choice",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["公民义务"],
    "question": "依法服兵役是：",
    "options": ["大人们的义务", "成年人的义务", "中华人民共和国公民的基本义务", "自愿的行为"],
    "answer": "中华人民共和国公民的基本义务",
    "explanation": "依照法律服兵役是中华人民共和国公民的基本义务，体现了公民对国家的责任",
  },
  {
    "id": "politics-039",
    "type": "choice",
    "subject": "politics",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["情绪调节"],
    "question": "情绪ABC理论中，A代表：",
    "options": ["情绪", "诱发性事件", "信念和想法", "行为和结果"],
    "answer": "诱发性事件",
    "explanation": "情绪ABC理论：A是诱发性事件（Activating event），B是信念和想法（Belief），C是行为和结果（Consequence）",
  },
  {
    "id": "politics-040",
    "type": "fill",
    "subject": "politics",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["法律意识"],
    "question": "《中华人民共和国未成年人保护法》从1992年1月1日起施行，于2007年和2012年进行了两次_____。",
    "answer": "修订",
    "explanation": "《未成年人保护法》于2007年和2012年进行了修订，不断完善对未成年人的保护",
  },
];