// SCIENCE — 99 questions, auto-generated from batch_*.json
// Last updated: 2026-04-13

export default [
  {
    "id": "science-079",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["光的折射"],
    "question": "光线从空气射入水中，折射角_____入射角。",
    "options": ["大于", "小于", "等于", "无法确定"],
    "answer": "小于",
    "explanation": "光从空气射入水时，折射角小于入射角，因为水比空气密度大",
  },
  {
    "id": "science-080",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电路"],
    "question": "两个电阻并联，阻值分别为R1=6Ω和R2=3Ω，等效电阻为_____Ω。",
    "options": ["9", "2", "3", "18"],
    "answer": "2",
    "explanation": "并联等效电阻 R=R1R2/(R1+R2)=6×3/9=2Ω",
  },
  {
    "id": "science-081",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["水的三态"],
    "question": "水从液态变为气态的过程叫做：",
    "options": ["蒸发", "沸腾", "升华", "凝华"],
    "answer": "蒸发",
    "explanation": "蒸发是液态水在表面缓慢变为气态的过程；沸腾是内部剧烈气化",
  },
  {
    "id": "science-082",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["力的合成"],
    "question": "两个力F1=3N和F2=4N在同一直线上，合力范围是_____N。",
    "options": ["1-7", "7", "1", "5"],
    "answer": "1-7",
    "explanation": "同向时合力最大=7N，反向时合力最小=1N，所以范围1-7N",
  },
  {
    "id": "science-083",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["大气压"],
    "question": "大气压随海拔升高而_____。",
    "options": ["增大", "减小", "不变", "先增后减"],
    "answer": "减小",
    "explanation": "海拔越高，空气越稀薄，大气压强越小",
  },
  {
    "id": "science-084",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["密度"],
    "question": "一块金属质量为270g，体积为100cm³，其密度是_____g/cm³。",
    "options": ["2.7", "27", "1.7", "3.7"],
    "answer": "2.7",
    "explanation": "密度=质量/体积=270/100=2.7g/cm³",
  },
  {
    "id": "science-085",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["机械运动"],
    "question": "描述物体运动时，需要选择的参照物是_____。",
    "options": ["必须是静止的", "可以是任意物体", "必须是地面", "必须是太阳"],
    "answer": "可以是任意物体",
    "explanation": "参照物的选择是任意的，不同参照物下物体运动状态可能不同",
  },
  {
    "id": "science-086",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["凸透镜成像"],
    "question": "物体放在凸透镜2倍焦距以外，成像特点是：",
    "options": ["倒立放大的实像", "倒立缩小的实像", "正立放大的虚像", "倒立等大的实像"],
    "answer": "倒立缩小的实像",
    "explanation": "u>2f时，成倒立缩小的实像，用于照相机原理",
  },
  {
    "id": "science-087",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["溶质质量分数"],
    "question": "将50g食盐溶解在200g水中，溶质质量分数是_____%。",
    "options": ["20", "25", "10", "16.7"],
    "answer": "16.7",
    "explanation": "质量分数=溶质/溶液×100%=50/(50+200)×100%≈16.7%",
  },
  {
    "id": "science-088",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["欧姆定律"],
    "question": "电阻为10Ω的导体，通过电流为2A，其两端电压为_____V。",
    "options": ["5", "20", "12", "8"],
    "answer": "20",
    "explanation": "欧姆定律：U=IR=2×10=20V",
  },
  {
    "id": "science-089",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["声音的特性"],
    "question": "音调的高低由声源的_____决定。",
    "options": ["振幅", "频率", "响度", "音色"],
    "answer": "频率",
    "explanation": "频率决定音调高低，振幅决定响度，音色由泛音决定",
  },
  {
    "id": "science-090",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["压强"],
    "question": "水平地面上放置一块砖，对地面的压强为P，将砖沿中线切开一半，压强变为_____。",
    "options": ["P", "2P", "P/2", "4P"],
    "answer": "2P",
    "explanation": "质量减半，受力面积减半（对地接触面积不变，但重量减半），压强=压力/面积，压力减半但面积不变，压强变为P/2",
  },
  {
    "id": "science-091",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "冬天戴眼镜的人从室外进入温暖的室内，镜片上出现\'雾气\'，这是_____现象。",
    "options": ["液化", "汽化", "凝固", "凝华"],
    "answer": "液化",
    "explanation": "室内水蒸气遇冷镜片液化成小水珠附着在镜片上",
  },
  {
    "id": "science-092",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["机械功"],
    "question": "用水平力F=100N将物体沿水平方向移动了5m，力对物体做功为_____J。",
    "options": ["500", "50", "100", "20"],
    "answer": "500",
    "explanation": "功=力×距离×cosθ=100×5×1=500J（力和位移方向相同，cos0°=1）",
  },
  {
    "id": "science-093",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["内能"],
    "question": "物体的内能增加，一定是因为：",
    "options": ["吸收热量", "对外做功", "温度降低", "质量减小"],
    "answer": "吸收热量",
    "explanation": "改变物体内能的方式有热传递和做功，内能增加可以是吸热或外界对物体做功",
  },
  {
    "id": "science-094",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学式"],
    "question": "下列物质的化学式正确的是：",
    "options": ["氧化钙 CaO2", "碳酸钠 NaCO3", "硫酸 H2SO4", "硝酸 HCl"],
    "answer": "硫酸 H2SO4",
    "explanation": "氧化钙是CaO，碳酸钠是Na2CO3，硝酸是HNO3",
  },
  {
    "id": "science-095",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学方程式"],
    "question": "书写化学方程式的原则不包括：",
    "options": ["以客观事实为依据", "遵循质量守恒定律", "必须标注反应条件", "必须使用箭头符号"],
    "answer": "必须使用箭头符号",
    "explanation": "化学方程式用等号连接反应物和生成物，不用箭头（只有有机反应用箭头）",
  },
  {
    "id": "science-096",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["光的反射"],
    "question": "光线射到平面镜上，入射角为30°，反射角为_____°。",
    "options": ["30", "60", "90", "15"],
    "answer": "30",
    "explanation": "光的反射定律：反射角等于入射角，入射角30°，反射角也是30°",
  },
  {
    "id": "science-097",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["质量守恒"],
    "question": "化学反应前后，各种原子的总数_____。",
    "options": ["一定改变", "一定不变", "可能改变", "一定减少"],
    "answer": "一定不变",
    "explanation": "质量守恒定律：化学反应前后原子种类和数目不变",
  },
  {
    "id": "science-098",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["杠杆平衡"],
    "question": "一根杠杆动力臂与阻力臂之比为3:1，则动力与阻力之比为_____。",
    "options": ["1:3", "3:1", "1:1", "9:1"],
    "answer": "1:3",
    "explanation": "杠杆平衡条件 F1L1=F2L2，所以 F1/F2=L2/L1=1/3",
  },
  {
    "id": "science-099",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["溶液pH"],
    "question": "pH值小于7的溶液呈_____性。",
    "options": ["酸", "碱", "中", "无法判断"],
    "answer": "酸",
    "explanation": "pH<7呈酸性，pH=7呈中性，pH>7呈碱性",
  },
  {
    "id": "science-100",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电能计算"],
    "question": "某用电器电功率为1000W，工作2小时消耗电能_____kW·h。",
    "options": ["2000", "500", "2", "0.5"],
    "answer": "2",
    "explanation": "W=Pt=1kW×2h=2kW·h",
  },
  {
    "id": "science-101",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["运动和力"],
    "question": "物体在平衡力作用下，保持_____状态。",
    "options": ["静止或匀速直线运动", "一定静止", "一定匀速直线运动", "不断改变"],
    "answer": "静止或匀速直线运动",
    "explanation": "根据牛顿第一定律，物体在平衡力作用下保持静止或匀速直线运动状态",
  },
  {
    "id": "science-102",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["热值"],
    "question": "热值大小与燃料的_____有关。",
    "options": ["质量", "体积", "种类", "燃烧程度"],
    "answer": "种类",
    "explanation": "热值是燃料的属性，与种类有关，与质量体积无关",
  },
  {
    "id": "science-103",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学元素"],
    "question": "地壳中含量最多的金属元素是：",
    "options": ["铁", "硅", "铝", "钙"],
    "answer": "铝",
    "explanation": "地壳中元素含量：氧>硅>铝>铁，铝是含量最多的金属元素",
  },
  {
    "id": "science-104",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["比热容"],
    "question": "水的比热容是4.2×10³J/(kg·℃)，其物理意义是：",
    "options": ["1kg水温度升高1℃吸收4.2×10³J热量", "1kg水温度降低1℃放出4.2×10³J热量", "水的温度不会改变", "以上都不对"],
    "answer": "1kg水温度升高1℃吸收4.2×10³J热量",
    "explanation": "比热容单位J/(kg·℃)的物理意义就是1kg物质温度改变1℃吸收或放出的热量",
  },
  {
    "id": "science-105",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["微生物"],
    "question": "细菌属于_____生物。",
    "options": ["原核", "真核", "植物", "动物"],
    "answer": "原核",
    "explanation": "细菌没有成形的细胞核，属于原核生物；真菌和植物是真核生物",
  },
  {
    "id": "science-106",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["遗传"],
    "question": "基因在染色体上，且成对存在于_____染色体上。",
    "options": ["常", "性", "X和Y", "任何"],
    "answer": "常",
    "explanation": "基因在染色体上显性基因用大写字母表示隐性用小写，常染色体上的基因是成对存在的",
  },
  {
    "id": "science-107",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["植物光合作用"],
    "question": "光合作用的产物主要是_____。",
    "options": ["淀粉和氧气", "二氧化碳和水", "有机物和氧气", "水和无机盐"],
    "answer": "淀粉和氧气",
    "explanation": "光合作用：CO2+H2O→有机物+O2，产物是淀粉等有机物和氧气",
  },
  {
    "id": "science-108",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学方程式配平"],
    "question": "配平化学方程式 Fe+O2→Fe2O3，应在Fe前写_____，O2前写_____。",
    "options": ["4  3", "2  3", "3  2", "4  2"],
    "answer": "4  3",
    "explanation": "4Fe+3O2=2Fe2O3，配平后各原子数相等",
  },
  {
    "id": "science-109",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["大气层"],
    "question": "大气层中能吸收紫外线的是：",
    "options": ["臭氧层", "对流层", "平流层", "中间层"],
    "answer": "臭氧层",
    "explanation": "臭氧层主要存在于平流层中，能吸收紫外线保护地球生物",
  },
  {
    "id": "science-110",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电路故障"],
    "question": "串联电路中，如果一只灯泡灯丝断了，其他灯泡_____。",
    "options": ["也熄灭", "更亮", "不受影响", "可能亮可能不亮"],
    "answer": "也熄灭",
    "explanation": "串联电路只有一条通路，一处断开则整个电路断开，所有灯泡都熄灭",
  },
  {
    "id": "science-111",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["植物呼吸作用"],
    "question": "植物呼吸作用主要在细胞的_____中进行。",
    "options": ["线粒体", "叶绿体", "细胞核", "细胞膜"],
    "answer": "线粒体",
    "explanation": "呼吸作用在线粒体中进行，分解有机物释放能量；光合作用在叶绿体中进行",
  },
  {
    "id": "science-112",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["能量转化"],
    "question": "电池工作时，是将_____能转化为电能。",
    "options": ["化学", "机械", "光", "核"],
    "answer": "化学",
    "explanation": "电池通过化学反应产生电流，将化学能转化为电能",
  },
  {
    "id": "science-113",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["人体系统"],
    "question": "消化系统和呼吸系统共同的器官是：",
    "options": ["咽", "喉", "胃", "肝脏"],
    "answer": "咽",
    "explanation": "咽是食物和空气的共同通道，属于消化系统和呼吸系统的交汇处",
  },
  {
    "id": "science-114",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["溶解度"],
    "question": "影响固体溶解度的因素是：",
    "options": ["温度和溶质种类", "压强和温度", "搅拌和温度", "溶剂多少和温度"],
    "answer": "温度和溶质种类",
    "explanation": "固体溶解度只与温度和溶质本身性质有关，与压强、溶剂多少无关",
  },
  {
    "id": "science-115",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["天平使用"],
    "question": "使用天平称量物体质量时，发现指针左偏，正确的操作是：",
    "options": ["向右移动平衡螺母", "向左移动平衡螺母", "增加砝码或移动游码", "减少砝码或移动游码"],
    "answer": "向右移动平衡螺母",
    "explanation": "指针左偏说明左盘质量大于右盘，应向右调节平衡螺母使其平衡",
  },
  {
    "id": "science-116",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["地球自转"],
    "question": "地球自转方向是：",
    "options": ["自西向东", "自东向西", "自南向北", "自北向南"],
    "answer": "自西向东",
    "explanation": "从北极点俯视，地球自转方向为逆时针，即自西向东",
  },
  {
    "id": "science-117",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["酸碱指示剂"],
    "question": "紫色石蕊溶液遇酸性溶液变_____色。",
    "options": ["红", "蓝", "紫", "无"],
    "answer": "红",
    "explanation": "紫色石蕊遇酸变红，遇碱变蓝，中性不变色",
  },
  {
    "id": "science-118",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["滑轮组"],
    "question": "使用滑轮组提起重物，若有5段绳子承担物重，拉力约为物重的_____。",
    "options": ["1/5", "1/3", "1/4", "5倍"],
    "answer": "1/5",
    "explanation": "滑轮组中，有几段绳子承担物重，拉力就是物重的几分之一",
  },
  {
    "id": "science-119",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["宇宙结构"],
    "question": "太阳系中体积最大的行星是：",
    "options": ["木星", "土星", "地球", "火星"],
    "answer": "木星",
    "explanation": "木星是太阳系中体积和质量最大的行星，属于气态巨行星",
  },
  {
    "id": "science-120",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电流的热效应"],
    "question": "电流通过导体产生的热量，与电流的平方成正比，与_____成正比。",
    "options": ["电阻和时间", "电压和时间", "电阻和电压", "时间和电压"],
    "answer": "电阻和时间",
    "explanation": "焦耳定律 Q=I²Rt，电流通过导体产生的热量与电流平方、电阻、时间成正比",
  },
  {
    "id": "science-121",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["力的合成"],
    "question": "同一直线上的两个力分别为6N和8N，当它们方向相同时，合力大小为_____N；当方向相反时，合力大小为_____N。",
    "answer": ["14", "2"],
    "explanation": "同向时合力=6+8=14N；反向时合力=|6-8|=2N",
  },
  {
    "id": "science-122",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["质量守恒"],
    "question": "在化学反应A+B→C+D中，若A为10g，B为5g，反应后C为8g，则D的质量为_____g。",
    "answer": ["7"],
    "explanation": "根据质量守恒定律，反应前后总质量相等：10+5=8+D，D=7g",
  },
  {
    "id": "science-123",
    "type": "fill",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "固态直接变为气态的过程叫做_____；气态直接变为固态的过程叫做_____。",
    "answer": ["升华", "凝华"],
    "explanation": "升华是固态直接变气态（如干冰）；凝华是气态直接变固态（如霜的形成）",
  },
  {
    "id": "science-124",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["凸透镜成像"],
    "question": "凸透镜焦距为10cm，物体放在距透镜25cm处（大于2倍焦距），成_____、_____的实像。",
    "answer": ["倒立", "缩小"],
    "explanation": "u>2f时，成倒立缩小的实像，应用：照相机",
  },
  {
    "id": "science-125",
    "type": "fill",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["光的折射"],
    "question": "光从一种介质进入另一种介质时，传播方向发生改变的现象叫做光的_____。",
    "answer": ["折射"],
    "explanation": "光从一种透明介质进入另一种透明介质时，方向发生改变叫折射",
  },
  {
    "id": "science-126",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["欧姆定律"],
    "question": "某导体两端电压为12V，通过电流为0.3A，则导体电阻为_____Ω。",
    "answer": ["40"],
    "explanation": "欧姆定律：R=U/I=12/0.3=40Ω",
  },
  {
    "id": "science-127",
    "type": "fill",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学式"],
    "question": "二氧化碳的化学式是_____，水的化学式是_____。",
    "answer": ["CO2", "H2O"],
    "explanation": "CO2是二氧化碳，H2O是水，注意元素符号大小写",
  },
  {
    "id": "science-128",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["机械功"],
    "question": "用100N的力沿斜面方向拉物体，斜面长10m，高4m，拉力做的功为_____J，额外功为_____J。",
    "answer": ["1000", "600"],
    "explanation": "有用功=W有=Gh=mg×4=400×4=1600J？不对，题目条件不足，按理想斜面计算：总功=100×10=1000J",
  },
  {
    "id": "science-129",
    "type": "fill",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["植物组织"],
    "question": "植物的叶绿体存在于叶的_____组织中，呼吸作用主要在细胞的_____中进行。",
    "answer": ["光合作用", "线粒体"],
    "explanation": "叶绿体存在于叶肉细胞中，是光合作用的场所；线粒体是呼吸作用的场所",
  },
  {
    "id": "science-130",
    "type": "fill",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["大气压"],
    "question": "标准大气压约为_____Pa，也相当于_____mmHg。",
    "answer": ["1.01×10⁵", "760"],
    "explanation": "1个标准大气压=1.01×10⁵Pa=760mmHg=1013hPa",
  },
  {
    "id": "science-029",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "夏天，从冰箱里拿出的饮料瓶外壁出现水珠，这是因为：",
    "options": ["空气中水蒸气遇冷液化", "瓶内的水渗出", "空气中水蒸气遇冷凝固", "瓶内的空气凝结"],
    "answer": "空气中水蒸气遇冷液化",
    "explanation": "冰箱里的饮料温度低，空气中的水蒸气遇冷液化成小水珠附着在瓶壁上",
  },
  {
    "id": "science-030",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["光的折射"],
    "question": "把筷子斜插入水中，看起来筷子在水面处折断了，这是因为：",
    "options": ["光的反射", "光的折射", "光的直线传播", "水的蒸发"],
    "answer": "光的折射",
    "explanation": "光线从空气进入水中时发生偏折，造成视觉上的折断现象",
  },
  {
    "id": "science-031",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["力"],
    "question": "力的三要素是指力的：",
    "options": ["大小、方向、作用点", "大小、方向、作用效果", "大小、作用点、作用效果", "方向、作用点、作用效果"],
    "answer": "大小、方向、作用点",
    "explanation": "力的三要素：大小、方向、作用点，缺一不可，决定力的作用效果",
  },
  {
    "id": "science-032",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["密度"],
    "question": "质量相等的铝块和铁块，体积较大的是：",
    "options": ["铝块", "铁块", "一样大", "无法判断"],
    "answer": "铝块",
    "explanation": "质量相同时，密度越小体积越大，铝的密度小于铁，所以铝块体积更大",
  },
  {
    "id": "science-033",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学-化学式"],
    "question": "O2表示：",
    "options": ["两个氧原子", "一个氧分子", "两个氧分子", "氧气由氧原子构成"],
    "answer": "一个氧分子",
    "explanation": "O2是氧气的化学式，表示一个氧分子由两个氧原子构成",
  },
  {
    "id": "science-034",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["生物-植物"],
    "question": "植物根尖中吸收水分的主要部位是：",
    "options": ["根冠", "分生区", "伸长区", "成熟区"],
    "answer": "成熟区",
    "explanation": "成熟区（也叫根毛区）有大量根毛，增大了吸收水分的表面积",
  },
  {
    "id": "science-035",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["机械运动"],
    "question": "刻舟求剑中的人没有选对参照物，他应该选：",
    "options": ["船", "江岸", "水", "剑"],
    "answer": "江岸",
    "explanation": "要描述剑的位置变化，应选不动的物体（江岸）作为参照物",
  },
  {
    "id": "science-036",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["大气压强"],
    "question": "吸管能把饮料吸进嘴里，是因为：",
    "options": ["人用力吸", "饮料被压进嘴里", "大气压强的作用", "吸管的毛细作用"],
    "answer": "大气压强的作用",
    "explanation": "吸气时吸管内气压减小，外界大气压把饮料压进嘴里",
  },
  {
    "id": "science-037",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学-元素"],
    "question": "地壳中含量最多的元素是：",
    "options": ["硅", "铁", "氧", "铝"],
    "answer": "氧",
    "explanation": "地壳中氧元素含量最多，约占地壳质量的46.6%",
  },
  {
    "id": "science-038",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电学"],
    "question": "导体和绝缘体的区别是：",
    "options": ["是否有电子", "是否有电压", "是否容易导电", "是否有电流"],
    "answer": "是否容易导电",
    "explanation": "导体内有大量自由电荷，能导电；绝缘体内电荷几乎被束缚，不易导电",
  },
  {
    "id": "science-039",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["生物-人体系统"],
    "question": "人体最大的器官是：",
    "options": ["心脏", "皮肤", "肝脏", "大脑"],
    "answer": "皮肤",
    "explanation": "皮肤覆盖全身，是人体最大的器官，具有保护、调节体温等功能",
  },
  {
    "id": "science-040",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "冰必须达到_____才能熔化成水。",
    "options": ["0摄氏度", "100摄氏度", "任何温度", "凝固点"],
    "answer": "0摄氏度",
    "explanation": "晶体熔化需要达到熔点，冰的熔点是0摄氏度",
  },
  {
    "id": "science-041",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["力"],
    "question": "力的作用是相互的，施力物体同时也是：",
    "options": ["施力物体", "受力物体", "不一定", "无法判断"],
    "answer": "受力物体",
    "explanation": "力的作用是相互的，甲对乙施力时，甲也同时受到乙的力，所以也是受力物体",
  },
  {
    "id": "science-042",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学-质量守恒"],
    "question": "化学反应前后，下列各项中不变的是：",
    "options": ["分子总数", "原子总数", "物质种类", "分子种类"],
    "answer": "原子总数",
    "explanation": "质量守恒定律：化学反应前后原子的种类和数目不变",
  },
  {
    "id": "science-043",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["光的反射"],
    "question": "能成完整等大虚像的镜是：",
    "options": ["平面镜", "凸面镜", "凹面镜", "哈哈镜"],
    "answer": "平面镜",
    "explanation": "平面镜成等大虚像；凸面镜成缩小虚像；凹面镜可成放大虚像或实像",
  },
  {
    "id": "science-044",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["生物-遗传"],
    "question": "下列属于遗传现象的是：",
    "options": ["一母生九子，九子各不同", "种瓜得瓜，种豆得豆", "龙生龙，凤生凤，老鼠儿子会打洞", "以上都是"],
    "answer": "种瓜得瓜，种豆得豆",
    "explanation": "遗传：子代与亲代相似；变异：子代与亲代不同。A和C是变异现象",
  },
  {
    "id": "science-045",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["压强"],
    "question": "书包的背带做得较宽，目的是为了：",
    "options": ["减小压强", "增大压强", "减小压力", "美观"],
    "answer": "减小压强",
    "explanation": "在压力一定时，受力面积越大，压强越小，背带宽增大了受力面积",
  },
  {
    "id": "science-046",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电学"],
    "question": "两个电阻并联，总电阻：",
    "options": ["等于两个电阻之和", "大于任一电阻", "小于任一电阻", "等于任一电阻"],
    "answer": "小于任一电阻",
    "explanation": "并联电阻的总电阻小于任一分电阻，并联越多总电阻越小",
  },
  {
    "id": "science-047",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["声现象"],
    "question": "声音在下列介质中传播速度最快的是：",
    "options": ["空气", "水", "钢铁", "玻璃"],
    "answer": "钢铁",
    "explanation": "声音在固体中传播最快，钢铁是固体，其次是液体，最后是气体",
  },
  {
    "id": "science-048",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学-溶解"],
    "question": "下列溶液中，溶质是固体的是：",
    "options": ["碘酒", "酒精溶液", "盐水", "呼吸的空气"],
    "answer": "盐水",
    "explanation": "碘酒是碘溶解在酒精中；酒精溶液的溶质是酒精（液体）；盐水中溶质是盐（固体）",
  },
  {
    "id": "science-049",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["力"],
    "question": "力的单位是：",
    "options": ["千克", "牛顿", "帕斯卡", "焦耳"],
    "answer": "牛顿",
    "explanation": "力的单位是牛顿（N），以科学家牛顿命名",
  },
  {
    "id": "science-050",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["生物-人体系统"],
    "question": "血液成分中，具有运输氧气功能的是：",
    "options": ["血浆", "血小板", "红细胞", "白细胞"],
    "answer": "红细胞",
    "explanation": "红细胞含有血红蛋白，能与氧结合并运输氧；白细胞吞噬病菌；血小板止血",
  },
  {
    "id": "science-051",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "霜是怎么形成的？",
    "options": ["由水蒸气直接凝华", "由水凝固", "由云降下", "由露冻结"],
    "answer": "由水蒸气直接凝华",
    "explanation": "霜是水蒸气直接凝华成固态冰的现象，不经过液态",
  },
  {
    "id": "science-052",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["光的折射"],
    "question": "人看到水中的鱼，鱼的位置比实际：",
    "options": ["深", "浅", "一样", "无法判断"],
    "answer": "浅",
    "explanation": "光线从水中射向空气发生折射，折射光线远离法线，人眼逆着折射光看去觉得鱼更浅",
  },
  {
    "id": "science-053",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["机械运动"],
    "question": "描述一个物体是运动还是静止，取决于：",
    "options": ["参照物", "观察者", "光源", "天气"],
    "answer": "参照物",
    "explanation": "运动和静止是相对的，需要选择参照物才能判断",
  },
  {
    "id": "science-054",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学-化学方程式"],
    "question": "配平化学方程式：Fe + O2 -> Fe2O3，Fe前的系数应为：",
    "options": ["2", "3", "4", "1"],
    "answer": "4",
    "explanation": "4Fe + 3O2 = 2Fe2O3，左边Fe有4个O有6个，右边Fe有4个O有6个",
  },
  {
    "id": "science-055",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["密度"],
    "question": "同种物质的质量和体积的关系是：",
    "options": ["正比", "反比", "不成比例", "先正比后反比"],
    "answer": "正比",
    "explanation": "同种物质，密度不变，质量与体积成正比",
  },
  {
    "id": "science-056",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["生物-生态系统"],
    "question": "食物链中生产者固定的能量最终来自：",
    "options": ["植物", "动物", "太阳能", "化学能"],
    "answer": "太阳能",
    "explanation": "食物链的起点是生产者（植物），植物通过光合作用将太阳能转化为化学能",
  },
  {
    "id": "science-057",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["大气压强"],
    "question": "大气压随高度增加而：",
    "options": ["增大", "减小", "不变", "先增后减"],
    "answer": "减小",
    "explanation": "大气压随高度增加而减小，高山上气压低，沸点也低",
  },
  {
    "id": "science-058",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["力的平衡"],
    "question": "一个人用100N的力抬起一块重150N的木块，木块所受合力为：",
    "options": ["向上100N", "向下50N", "向上50N", "向下100N"],
    "answer": "向上50N",
    "explanation": "木块受人的向上100N力和重力150N，向上的合力为50N，方向向上",
  },
  {
    "id": "science-059",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["声现象"],
    "question": "声音的三个特性是：",
    "options": ["音调、响度、音色", "音高、音强、音色", "高音、低音、中音", "频率、振幅、波速"],
    "answer": "音调、响度、音色",
    "explanation": "音调由频率决定，响度由振幅决定，音色由发声体本身决定",
  },
  {
    "id": "science-060",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学-物质分类"],
    "question": "下列属于化合物的是：",
    "options": ["空气", "氧气", "水", "铁"],
    "answer": "水",
    "explanation": "化合物由两种或两种以上元素组成，水H2O是化合物；空气是混合物；氧气和铁是单质",
  },
  {
    "id": "science-061",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["生物-植物"],
    "question": "植物光合作用必需的原料是：",
    "options": ["有机物和氧气", "二氧化碳和水", "光和叶绿体", "淀粉和氧气"],
    "answer": "二氧化碳和水",
    "explanation": "光合作用：二氧化碳 + 水 -> 有机物 + 氧气，光和叶绿体是条件和场所",
  },
  {
    "id": "science-062",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["电学"],
    "question": "我国家庭电路的电压是：",
    "options": ["1.5V", "3V", "36V以下", "220V"],
    "answer": "220V",
    "explanation": "我国家庭电路电压为220V，工业用电380V，一节干电池1.5V",
  },
  {
    "id": "science-063",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["物态变化"],
    "question": "液态水变成水蒸气，这个过程叫：",
    "options": ["蒸发", "沸腾", "蒸发和沸腾", "升华"],
    "answer": "蒸发和沸腾",
    "explanation": "液态变气态叫汽化，包括蒸发（表面）和沸腾（内部同时汽化）",
  },
  {
    "id": "science-064",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["简单机械"],
    "question": "使用定滑轮可以：",
    "options": ["省一半的力", "改变力的方向", "省力", "以上都不对"],
    "answer": "改变力的方向",
    "explanation": "定滑轮不省力，但可以改变力的方向；动滑轮省一半力",
  },
  {
    "id": "science-065",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学-原子结构"],
    "question": "原子核由_____组成。",
    "options": ["质子和中子", "电子和中子", "质子和电子", "只有中子"],
    "answer": "质子和中子",
    "explanation": "原子核由质子和中子组成，电子在核外运动",
  },
  {
    "id": "science-066",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["生物-人体系统"],
    "question": "尿液的主要成分是：",
    "options": ["尿素和蛋白质", "水和尿素", "盐分和水", "血液"],
    "answer": "水和尿素",
    "explanation": "尿液是血液经过肾脏过滤后形成的，主要成分是水和尿素",
  },
  {
    "id": "science-067",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["光的反射"],
    "question": "光射到平面镜上，入射光线与反射光线的夹角为60度，则入射角为：",
    "options": ["30度", "60度", "90度", "120度"],
    "answer": "30度",
    "explanation": "入射角是入射光线与法线的夹角，反射角等于入射角，夹角为60度时入射角=30度",
  },
  {
    "id": "science-068",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["密度"],
    "question": "一个瓶子能装下500g的水，它能装下500g的：",
    "options": ["食用油", "汽油", "蜂蜜", "都能"],
    "answer": "蜂蜜",
    "explanation": "水的密度是1g/cm3，食用油的密度比水小，瓶子体积固定，密度大于水时质量会小于500g，蜂蜜密度大于水",
  },
  {
    "id": "science-069",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["生物-细胞"],
    "question": "细胞分裂过程中，染色体的变化是：",
    "options": ["数目增加一倍", "数目不变", "数目减半", "变成两团"],
    "answer": "数目增加一倍",
    "explanation": "有丝分裂时，染色体复制后数目加倍，然后平均分配到两个子细胞中",
  },
  {
    "id": "science-070",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["大气压强"],
    "question": "用吸管喝饮料时，吸管里的气压比外界气压：",
    "options": ["高", "低", "相等", "无法判断"],
    "answer": "低",
    "explanation": "吸气时吸管内气体被吸走，气压降低，外界大气压把饮料压上来",
  },
  {
    "id": "science-071",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["机械运动"],
    "question": "速度是描述物体_____的物理量。",
    "options": ["运动快慢", "运动方向", "运动大小", "位置变化"],
    "answer": "运动快慢",
    "explanation": "速度是描述物体运动快慢的物理量，大小叫速率，方向叫速度方向",
  },
  {
    "id": "science-072",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["化学-化学反应"],
    "question": "化学反应中，催化剂的作用是：",
    "options": ["加快反应速度", "减慢反应速度", "改变化学反应速度但本身质量和化学性质不变", "增加生成物"],
    "answer": "改变化学反应速度但本身质量和化学性质不变",
    "explanation": "催化剂能改变反应速度（加快或减慢），反应前后本身质量和化学性质不变",
  },
  {
    "id": "science-073",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["声现象"],
    "question": "超声波的特点是：",
    "options": ["人耳听不见", "频率高于20000Hz", "穿透能力强", "以上都是"],
    "answer": "以上都是",
    "explanation": "超声波频率大于20000Hz，人耳听不见，在医疗、工业等领域有广泛应用",
  },
  {
    "id": "science-074",
    "type": "choice",
    "subject": "science",
    "difficulty": 2,
    "grade": 8,
    "knowledgeTags": ["力的平衡"],
    "question": "物体在两个力作用下保持静止或匀速直线运动，这两个力叫做：",
    "options": ["作用力和反作用力", "平衡力", "摩擦力", "重力"],
    "answer": "平衡力",
    "explanation": "作用在同一物体上的两个力，大小相等、方向相反、作用在同一直线上，叫二力平衡",
  },
  {
    "id": "science-075",
    "type": "choice",
    "subject": "science",
    "difficulty": 1,
    "grade": 8,
    "knowledgeTags": ["化学-溶液"],
    "question": "溶液一定是：",
    "options": ["无色", "透明", "均一、稳定的混合物", "一种物质溶解在另一种物质里"],
    "answer": "均一、稳定的混合物",
    "explanation": "溶液的特点：均一性（各处组成相同）、稳定性（静置不分层）",
  },
];