// PRIMARY-ENGLISH — question bank
// Total: 182 questions
// Last updated: 2026-04-29

export default [
  {"id":"english-g3-001","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["字母认知"],"question":"Which is a capital letter?","options":[{"label":"A","text":"a"},{"label":"B","text":"B"},{"label":"C","text":"c"},{"label":"D","text":"d"}],"answer":"B","explanation":"本题涉及字母认知知识点。正确答案是B：B。"}
  {"id":"english-g3-002","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["26个字母"],"question":"Which of the following is correct about 26个字母?","options":[{"label":"A","text":"26个字母 is an important part of 语音与词汇"},{"label":"B","text":"26个字母 belongs to another category"},{"label":"C","text":"26个字母 is not related to 语音与词汇"},{"label":"D","text":"26个字母 is only used in special situations"}],"answer":"A","explanation":"26个字母是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-004","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇识记"],"question":"What does 'apple' mean?","options":[{"label":"A","text":"苹果"},{"label":"B","text":"香蕉"},{"label":"C","text":"橙子"},{"label":"D","text":"葡萄"}],"answer":"A","explanation":"本题涉及词汇识记知识点。正确答案是A：苹果。"}
  {"id":"english-g3-005","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["问候语"],"question":"Which of the following is correct about 问候语?","options":[{"label":"A","text":"问候语 is an important part of 口语交际"},{"label":"B","text":"问候语 belongs to another category"},{"label":"C","text":"问候语 is not related to 口语交际"},{"label":"D","text":"问候语 is only used in special situations"}],"answer":"A","explanation":"问候语是口语交际学习中的重要内容。"}
  {"id":"english-g3-007","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇拼写"],"question":"Choose the correct spelling:","options":[{"label":"A","text":"elephnt"},{"label":"B","text":"elephant"},{"label":"C","text":"elephent"},{"label":"D","text":"elefaunt"}],"answer":"B","explanation":"本题涉及词汇拼写知识点。正确答案是B：elephant。"}
  {"id":"english-g3-008","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["数字1-10"],"question":"Which of the following is correct about 数字1-10?","options":[{"label":"A","text":"数字1-10 is an important part of 语音与词汇"},{"label":"B","text":"数字1-10 belongs to another category"},{"label":"C","text":"数字1-10 is not related to 语音与词汇"},{"label":"D","text":"数字1-10 is only used in special situations"}],"answer":"A","explanation":"数字1-10是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-010","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["名词单复数"],"question":"He is a _____ (boy).","options":[{"label":"A","text":"girl"},{"label":"B","text":"boy"},{"label":"C","text":"teacher"},{"label":"D","text":"doctor"}],"answer":"B","explanation":"本题涉及名词单复数知识点。正确答案是B：boy。"}
  {"id":"english-g3-011","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["颜色单词"],"question":"Which of the following is correct about 颜色单词?","options":[{"label":"A","text":"颜色单词 is an important part of 语音与词汇"},{"label":"B","text":"颜色单词 belongs to another category"},{"label":"C","text":"颜色单词 is not related to 语音与词汇"},{"label":"D","text":"颜色单词 is only used in special situations"}],"answer":"A","explanation":"颜色单词是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-013","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["日常用语"],"question":"How are you? I am _____.","options":[{"label":"A","text":"sad"},{"label":"B","text":"fine"},{"label":"C","text":"cry"},{"label":"D","text":"bad"}],"answer":"B","explanation":"本题涉及日常用语知识点。正确答案是B：fine。"}
  {"id":"english-g3-014","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["家庭成员"],"question":"Which of the following is correct about 家庭成员?","options":[{"label":"A","text":"家庭成员 is an important part of 语音与词汇"},{"label":"B","text":"家庭成员 belongs to another category"},{"label":"C","text":"家庭成员 is not related to 语音与词汇"},{"label":"D","text":"家庭成员 is only used in special situations"}],"answer":"A","explanation":"家庭成员是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-016","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇反义词"],"question":"What is the opposite of 'big'?","options":[{"label":"A","text":"small"},{"label":"B","text":"tall"},{"label":"C","text":"long"},{"label":"D","text":"short"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：small。"}
  {"id":"english-g3-017","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["水果单词"],"question":"Which of the following is correct about 水果单词?","options":[{"label":"A","text":"水果单词 is an important part of 语音与词汇"},{"label":"B","text":"水果单词 belongs to another category"},{"label":"C","text":"水果单词 is not related to 语音与词汇"},{"label":"D","text":"水果单词 is only used in special situations"}],"answer":"A","explanation":"水果单词是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-019","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["一般现在时"],"question":"She _____ apples every day.","options":[{"label":"A","text":"eat"},{"label":"B","text":"eats"},{"label":"C","text":"eating"},{"label":"D","text":"ate"}],"answer":"B","explanation":"本题涉及一般现在时知识点。正确答案是B：eats。"}
  {"id":"english-g3-020","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["动物单词"],"question":"Which of the following is correct about 动物单词?","options":[{"label":"A","text":"动物单词 is an important part of 语音与词汇"},{"label":"B","text":"动物单词 belongs to another category"},{"label":"C","text":"动物单词 is not related to 语音与词汇"},{"label":"D","text":"动物单词 is only used in special situations"}],"answer":"A","explanation":"动物单词是语音与词汇学习中的重要内容。"}
  {"id":"english-g3-022","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["特殊疑问句"],"question":"_____ is your name? My name is Tom.","options":[{"label":"A","text":"What"},{"label":"B","text":"Who"},{"label":"C","text":"Where"},{"label":"D","text":"When"}],"answer":"A","explanation":"本题涉及特殊疑问句知识点。正确答案是A：What。"}
  {"id":"english-g3-023","type":"choice","subject":"english","difficulty":easy,"grade":3,"knowledgeTags":["日常用语"],"question":"Which of the following is correct about 日常用语?","options":[{"label":"A","text":"日常用语 is an important part of 口语交际"},{"label":"B","text":"日常用语 belongs to another category"},{"label":"C","text":"日常用语 is not related to 口语交际"},{"label":"D","text":"日常用语 is only used in special situations"}],"answer":"A","explanation":"日常用语是口语交际学习中的重要内容。"}
  {"id":"english-g3-025","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["可数不可数名词"],"question":"How many _____ (month) in a year?","options":[{"label":"A","text":"month"},{"label":"B","text":"months"},{"label":"C","text":"monthes"},{"label":"D","text":"monthed"}],"answer":"B","explanation":"本题涉及可数不可数名词知识点。正确答案是B：months。"}
  {"id":"english-g3-026","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["介词用法"],"question":"The cat is on the _____.","options":[{"label":"A","text":"desk"},{"label":"B","text":"table"},{"label":"C","text":"chair"},{"label":"D","text":"sofa"}],"answer":"A","explanation":"本题涉及介词用法知识点。正确答案是A：desk。"}
  {"id":"english-g3-027","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["there be句型"],"question":"There _____ some water in the glass.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}],"answer":"A","explanation":"本题涉及there be句型知识点。正确答案是A：is。"}
  {"id":"english-g3-028","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["名词变复数"],"question":"I have two _____ (child).","options":[{"label":"A","text":"child"},{"label":"B","text":"childs"},{"label":"C","text":"children"},{"label":"D","text":"childes"}],"answer":"C","explanation":"本题涉及名词变复数知识点。正确答案是C：children。"}
  {"id":"english-g3-029","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["比较级"],"question":"He is _____ than his brother.","options":[{"label":"A","text":"tall"},{"label":"B","text":"taller"},{"label":"C","text":"tallest"},{"label":"D","text":"more tall"}],"answer":"B","explanation":"本题涉及比较级知识点。正确答案是B：taller。"}
  {"id":"english-g3-030","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇反义词"],"question":"The opposite of 'hot' is _____.","options":[{"label":"A","text":"cold"},{"label":"B","text":"warm"},{"label":"C","text":"cool"},{"label":"D","text":"wet"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：cold。"}
  {"id":"english-g3-031","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["数词用法"],"question":"There are _____ days in a week.","options":[{"label":"A","text":"five"},{"label":"B","text":"six"},{"label":"C","text":"seven"},{"label":"D","text":"eight"}],"answer":"C","explanation":"本题涉及数词用法知识点。正确答案是C：seven。"}
  {"id":"english-g3-032","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["句型辨析"],"question":"Which sentence is correct?","options":[{"label":"A","text":"He don't like fish."},{"label":"B","text":"He doesn't like fish."},{"label":"C","text":"He not like fish."},{"label":"D","text":"He no like fish."}],"answer":"B","explanation":"本题涉及句型辨析知识点。正确答案是B：He doesn't like fish.。"}
  {"id":"english-g3-033","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["现在完成时"],"question":"She has lived in Shanghai _____ five years.","options":[{"label":"A","text":"for"},{"label":"B","text":"since"},{"label":"C","text":"in"},{"label":"D","text":"at"}],"answer":"A","explanation":"本题涉及现在完成时知识点。正确答案是A：for。"}
  {"id":"english-g3-034","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["情态动词"],"question":"Could you please _____ the door?","options":[{"label":"A","text":"open"},{"label":"B","text":"to open"},{"label":"C","text":"opening"},{"label":"D","text":"opened"}],"answer":"A","explanation":"本题涉及情态动词知识点。正确答案是A：open。"}
  {"id":"english-g3-035","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["定语从句"],"question":"The book _____ cover is red is mine.","options":[{"label":"A","text":"whose"},{"label":"B","text":"which"},{"label":"C","text":"who"},{"label":"D","text":"whom"}],"answer":"A","explanation":"本题涉及定语从句知识点。正确答案是A：whose。"}
  {"id":"english-g3-036","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["宾语从句"],"question":"He asked me _____ I was busy.","options":[{"label":"A","text":"if"},{"label":"B","text":"that"},{"label":"C","text":"what"},{"label":"D","text":"which"}],"answer":"A","explanation":"本题涉及宾语从句知识点。正确答案是A：if。"}
  {"id":"english-g4-001","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["字母认知"],"question":"Which is a capital letter?","options":[{"label":"A","text":"a"},{"label":"B","text":"B"},{"label":"C","text":"c"},{"label":"D","text":"d"}],"answer":"B","explanation":"本题涉及字母认知知识点。正确答案是B：B。"}
  {"id":"english-g4-002","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["词汇识记"],"question":"What does 'apple' mean?","options":[{"label":"A","text":"苹果"},{"label":"B","text":"香蕉"},{"label":"C","text":"橙子"},{"label":"D","text":"葡萄"}],"answer":"A","explanation":"本题涉及词汇识记知识点。正确答案是A：苹果。"}
  {"id":"english-g4-003","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["词汇拼写"],"question":"Choose the correct spelling:","options":[{"label":"A","text":"elephnt"},{"label":"B","text":"elephant"},{"label":"C","text":"elephent"},{"label":"D","text":"elefaunt"}],"answer":"B","explanation":"本题涉及词汇拼写知识点。正确答案是B：elephant。"}
  {"id":"english-g4-004","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["名词单复数"],"question":"He is a _____ (boy).","options":[{"label":"A","text":"girl"},{"label":"B","text":"boy"},{"label":"C","text":"teacher"},{"label":"D","text":"doctor"}],"answer":"B","explanation":"本题涉及名词单复数知识点。正确答案是B：boy。"}
  {"id":"english-g4-005","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["日常用语"],"question":"How are you? I am _____.","options":[{"label":"A","text":"sad"},{"label":"B","text":"fine"},{"label":"C","text":"cry"},{"label":"D","text":"bad"}],"answer":"B","explanation":"本题涉及日常用语知识点。正确答案是B：fine。"}
  {"id":"english-g4-006","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["词汇反义词"],"question":"What is the opposite of 'big'?","options":[{"label":"A","text":"small"},{"label":"B","text":"tall"},{"label":"C","text":"long"},{"label":"D","text":"short"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：small。"}
  {"id":"english-g4-007","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["一般现在时"],"question":"She _____ apples every day.","options":[{"label":"A","text":"eat"},{"label":"B","text":"eats"},{"label":"C","text":"eating"},{"label":"D","text":"ate"}],"answer":"B","explanation":"本题涉及一般现在时知识点。正确答案是B：eats。"}
  {"id":"english-g4-008","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["特殊疑问句"],"question":"_____ is your name? My name is Tom.","options":[{"label":"A","text":"What"},{"label":"B","text":"Who"},{"label":"C","text":"Where"},{"label":"D","text":"When"}],"answer":"A","explanation":"本题涉及特殊疑问句知识点。正确答案是A：What。"}
  {"id":"english-g4-009","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["可数不可数名词"],"question":"How many _____ (month) in a year?","options":[{"label":"A","text":"month"},{"label":"B","text":"months"},{"label":"C","text":"monthes"},{"label":"D","text":"monthed"}],"answer":"B","explanation":"本题涉及可数不可数名词知识点。正确答案是B：months。"}
  {"id":"english-g4-010","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["介词用法"],"question":"The cat is on the _____.","options":[{"label":"A","text":"desk"},{"label":"B","text":"table"},{"label":"C","text":"chair"},{"label":"D","text":"sofa"}],"answer":"A","explanation":"本题涉及介词用法知识点。正确答案是A：desk。"}
  {"id":"english-g4-011","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["there be句型"],"question":"There _____ some water in the glass.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}],"answer":"A","explanation":"本题涉及there be句型知识点。正确答案是A：is。"}
  {"id":"english-g4-012","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["名词变复数"],"question":"I have two _____ (child).","options":[{"label":"A","text":"child"},{"label":"B","text":"childs"},{"label":"C","text":"children"},{"label":"D","text":"childes"}],"answer":"C","explanation":"本题涉及名词变复数知识点。正确答案是C：children。"}
  {"id":"english-g4-013","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["比较级"],"question":"He is _____ than his brother.","options":[{"label":"A","text":"tall"},{"label":"B","text":"taller"},{"label":"C","text":"tallest"},{"label":"D","text":"more tall"}],"answer":"B","explanation":"本题涉及比较级知识点。正确答案是B：taller。"}
  {"id":"english-g4-014","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["词汇反义词"],"question":"The opposite of 'hot' is _____.","options":[{"label":"A","text":"cold"},{"label":"B","text":"warm"},{"label":"C","text":"cool"},{"label":"D","text":"wet"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：cold。"}
  {"id":"english-g4-015","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["数词用法"],"question":"There are _____ days in a week.","options":[{"label":"A","text":"five"},{"label":"B","text":"six"},{"label":"C","text":"seven"},{"label":"D","text":"eight"}],"answer":"C","explanation":"本题涉及数词用法知识点。正确答案是C：seven。"}
  {"id":"english-g4-016","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["句型辨析"],"question":"Which sentence is correct?","options":[{"label":"A","text":"He don't like fish."},{"label":"B","text":"He doesn't like fish."},{"label":"C","text":"He not like fish."},{"label":"D","text":"He no like fish."}],"answer":"B","explanation":"本题涉及句型辨析知识点。正确答案是B：He doesn't like fish.。"}
  {"id":"english-g4-017","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["现在完成时"],"question":"She has lived in Shanghai _____ five years.","options":[{"label":"A","text":"for"},{"label":"B","text":"since"},{"label":"C","text":"in"},{"label":"D","text":"at"}],"answer":"A","explanation":"本题涉及现在完成时知识点。正确答案是A：for。"}
  {"id":"english-g4-018","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["情态动词"],"question":"Could you please _____ the door?","options":[{"label":"A","text":"open"},{"label":"B","text":"to open"},{"label":"C","text":"opening"},{"label":"D","text":"opened"}],"answer":"A","explanation":"本题涉及情态动词知识点。正确答案是A：open。"}
  {"id":"english-g4-019","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["定语从句"],"question":"The book _____ cover is red is mine.","options":[{"label":"A","text":"whose"},{"label":"B","text":"which"},{"label":"C","text":"who"},{"label":"D","text":"whom"}],"answer":"A","explanation":"本题涉及定语从句知识点。正确答案是A：whose。"}
  {"id":"english-g4-020","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["宾语从句"],"question":"He asked me _____ I was busy.","options":[{"label":"A","text":"if"},{"label":"B","text":"that"},{"label":"C","text":"what"},{"label":"D","text":"which"}],"answer":"A","explanation":"本题涉及宾语从句知识点。正确答案是A：if。"}
  {"id":"english-g4-031","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["数字11-20"],"question":"Which of the following is correct about 数字11-20?","options":[{"label":"A","text":"数字11-20 is an important part of 语音与词汇"},{"label":"B","text":"数字11-20 belongs to another category"},{"label":"C","text":"数字11-20 is not related to 语音与词汇"},{"label":"D","text":"数字11-20 is only used in special situations"}],"answer":"A","explanation":"数字11-20是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-032","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["数字11-20"],"question":"Which of the following is correct about 数字11-20?","options":[{"label":"A","text":"数字11-20 is an important part of 语音与词汇"},{"label":"B","text":"数字11-20 belongs to another category"},{"label":"C","text":"数字11-20 is not related to 语音与词汇"},{"label":"D","text":"数字11-20 is only used in special situations"}],"answer":"A","explanation":"数字11-20是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-034","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["时间表达"],"question":"Which of the following is correct about 时间表达?","options":[{"label":"A","text":"时间表达 is an important part of 口语交际"},{"label":"B","text":"时间表达 belongs to another category"},{"label":"C","text":"时间表达 is not related to 口语交际"},{"label":"D","text":"时间表达 is only used in special situations"}],"answer":"A","explanation":"时间表达是口语交际学习中的重要内容。"}
  {"id":"english-g4-035","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["时间表达"],"question":"Which of the following is correct about 时间表达?","options":[{"label":"A","text":"时间表达 is an important part of 口语交际"},{"label":"B","text":"时间表达 belongs to another category"},{"label":"C","text":"时间表达 is not related to 口语交际"},{"label":"D","text":"时间表达 is only used in special situations"}],"answer":"A","explanation":"时间表达是口语交际学习中的重要内容。"}
  {"id":"english-g4-037","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["星期名称"],"question":"Which of the following is correct about 星期名称?","options":[{"label":"A","text":"星期名称 is an important part of 语音与词汇"},{"label":"B","text":"星期名称 belongs to another category"},{"label":"C","text":"星期名称 is not related to 语音与词汇"},{"label":"D","text":"星期名称 is only used in special situations"}],"answer":"A","explanation":"星期名称是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-038","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["星期名称"],"question":"Which of the following is correct about 星期名称?","options":[{"label":"A","text":"星期名称 is an important part of 语音与词汇"},{"label":"B","text":"星期名称 belongs to another category"},{"label":"C","text":"星期名称 is not related to 语音与词汇"},{"label":"D","text":"星期名称 is only used in special situations"}],"answer":"A","explanation":"星期名称是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-040","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["月份名称"],"question":"Which of the following is correct about 月份名称?","options":[{"label":"A","text":"月份名称 is an important part of 语音与词汇"},{"label":"B","text":"月份名称 belongs to another category"},{"label":"C","text":"月份名称 is not related to 语音与词汇"},{"label":"D","text":"月份名称 is only used in special situations"}],"answer":"A","explanation":"月份名称是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-041","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["月份名称"],"question":"Which of the following is correct about 月份名称?","options":[{"label":"A","text":"月份名称 is an important part of 语音与词汇"},{"label":"B","text":"月份名称 belongs to another category"},{"label":"C","text":"月份名称 is not related to 语音与词汇"},{"label":"D","text":"月份名称 is only used in special situations"}],"answer":"A","explanation":"月份名称是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-044","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["衣物单词"],"question":"Which of the following is correct about 衣物单词?","options":[{"label":"A","text":"衣物单词 is an important part of 语音与词汇"},{"label":"B","text":"衣物单词 belongs to another category"},{"label":"C","text":"衣物单词 is not related to 语音与词汇"},{"label":"D","text":"衣物单词 is only used in special situations"}],"answer":"A","explanation":"衣物单词是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-047","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["交通工具"],"question":"Which of the following is correct about 交通工具?","options":[{"label":"A","text":"交通工具 is an important part of 语音与词汇"},{"label":"B","text":"交通工具 belongs to another category"},{"label":"C","text":"交通工具 is not related to 语音与词汇"},{"label":"D","text":"交通工具 is only used in special situations"}],"answer":"A","explanation":"交通工具是语音与词汇学习中的重要内容。"}
  {"id":"english-g4-050","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["方位介词"],"question":"Which of the following is correct about 方位介词?","options":[{"label":"A","text":"方位介词 is an important part of 语法基础"},{"label":"B","text":"方位介词 belongs to another category"},{"label":"C","text":"方位介词 is not related to 语法基础"},{"label":"D","text":"方位介词 is only used in special situations"}],"answer":"A","explanation":"方位介词是语法基础学习中的重要内容。"}
  {"id":"english-g4-053","type":"choice","subject":"english","difficulty":easy,"grade":4,"knowledgeTags":["be动词"],"question":"Which of the following is correct about be动词?","options":[{"label":"A","text":"be动词 is an important part of 语法基础"},{"label":"B","text":"be动词 belongs to another category"},{"label":"C","text":"be动词 is not related to 语法基础"},{"label":"D","text":"be动词 is only used in special situations"}],"answer":"A","explanation":"be动词是语法基础学习中的重要内容。"}
  {"id":"english-g5-001","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["字母认知"],"question":"Which is a capital letter?","options":[{"label":"A","text":"a"},{"label":"B","text":"B"},{"label":"C","text":"c"},{"label":"D","text":"d"}],"answer":"B","explanation":"本题涉及字母认知知识点。正确答案是B：B。"}
  {"id":"english-g5-002","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["词汇识记"],"question":"What does 'apple' mean?","options":[{"label":"A","text":"苹果"},{"label":"B","text":"香蕉"},{"label":"C","text":"橙子"},{"label":"D","text":"葡萄"}],"answer":"A","explanation":"本题涉及词汇识记知识点。正确答案是A：苹果。"}
  {"id":"english-g5-003","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["词汇拼写"],"question":"Choose the correct spelling:","options":[{"label":"A","text":"elephnt"},{"label":"B","text":"elephant"},{"label":"C","text":"elephent"},{"label":"D","text":"elefaunt"}],"answer":"B","explanation":"本题涉及词汇拼写知识点。正确答案是B：elephant。"}
  {"id":"english-g5-004","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["名词单复数"],"question":"He is a _____ (boy).","options":[{"label":"A","text":"girl"},{"label":"B","text":"boy"},{"label":"C","text":"teacher"},{"label":"D","text":"doctor"}],"answer":"B","explanation":"本题涉及名词单复数知识点。正确答案是B：boy。"}
  {"id":"english-g5-005","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["日常用语"],"question":"How are you? I am _____.","options":[{"label":"A","text":"sad"},{"label":"B","text":"fine"},{"label":"C","text":"cry"},{"label":"D","text":"bad"}],"answer":"B","explanation":"本题涉及日常用语知识点。正确答案是B：fine。"}
  {"id":"english-g5-006","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["词汇反义词"],"question":"What is the opposite of 'big'?","options":[{"label":"A","text":"small"},{"label":"B","text":"tall"},{"label":"C","text":"long"},{"label":"D","text":"short"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：small。"}
  {"id":"english-g5-007","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["一般现在时"],"question":"She _____ apples every day.","options":[{"label":"A","text":"eat"},{"label":"B","text":"eats"},{"label":"C","text":"eating"},{"label":"D","text":"ate"}],"answer":"B","explanation":"本题涉及一般现在时知识点。正确答案是B：eats。"}
  {"id":"english-g5-008","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["特殊疑问句"],"question":"_____ is your name? My name is Tom.","options":[{"label":"A","text":"What"},{"label":"B","text":"Who"},{"label":"C","text":"Where"},{"label":"D","text":"When"}],"answer":"A","explanation":"本题涉及特殊疑问句知识点。正确答案是A：What。"}
  {"id":"english-g5-009","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["可数不可数名词"],"question":"How many _____ (month) in a year?","options":[{"label":"A","text":"month"},{"label":"B","text":"months"},{"label":"C","text":"monthes"},{"label":"D","text":"monthed"}],"answer":"B","explanation":"本题涉及可数不可数名词知识点。正确答案是B：months。"}
  {"id":"english-g5-010","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["介词用法"],"question":"The cat is on the _____.","options":[{"label":"A","text":"desk"},{"label":"B","text":"table"},{"label":"C","text":"chair"},{"label":"D","text":"sofa"}],"answer":"A","explanation":"本题涉及介词用法知识点。正确答案是A：desk。"}
  {"id":"english-g5-011","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["there be句型"],"question":"There _____ some water in the glass.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}],"answer":"A","explanation":"本题涉及there be句型知识点。正确答案是A：is。"}
  {"id":"english-g5-012","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["名词变复数"],"question":"I have two _____ (child).","options":[{"label":"A","text":"child"},{"label":"B","text":"childs"},{"label":"C","text":"children"},{"label":"D","text":"childes"}],"answer":"C","explanation":"本题涉及名词变复数知识点。正确答案是C：children。"}
  {"id":"english-g5-013","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["比较级"],"question":"He is _____ than his brother.","options":[{"label":"A","text":"tall"},{"label":"B","text":"taller"},{"label":"C","text":"tallest"},{"label":"D","text":"more tall"}],"answer":"B","explanation":"本题涉及比较级知识点。正确答案是B：taller。"}
  {"id":"english-g5-014","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["词汇反义词"],"question":"The opposite of 'hot' is _____.","options":[{"label":"A","text":"cold"},{"label":"B","text":"warm"},{"label":"C","text":"cool"},{"label":"D","text":"wet"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：cold。"}
  {"id":"english-g5-015","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["数词用法"],"question":"There are _____ days in a week.","options":[{"label":"A","text":"five"},{"label":"B","text":"six"},{"label":"C","text":"seven"},{"label":"D","text":"eight"}],"answer":"C","explanation":"本题涉及数词用法知识点。正确答案是C：seven。"}
  {"id":"english-g5-016","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["句型辨析"],"question":"Which sentence is correct?","options":[{"label":"A","text":"He don't like fish."},{"label":"B","text":"He doesn't like fish."},{"label":"C","text":"He not like fish."},{"label":"D","text":"He no like fish."}],"answer":"B","explanation":"本题涉及句型辨析知识点。正确答案是B：He doesn't like fish.。"}
  {"id":"english-g5-017","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["现在完成时"],"question":"She has lived in Shanghai _____ five years.","options":[{"label":"A","text":"for"},{"label":"B","text":"since"},{"label":"C","text":"in"},{"label":"D","text":"at"}],"answer":"A","explanation":"本题涉及现在完成时知识点。正确答案是A：for。"}
  {"id":"english-g5-018","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["情态动词"],"question":"Could you please _____ the door?","options":[{"label":"A","text":"open"},{"label":"B","text":"to open"},{"label":"C","text":"opening"},{"label":"D","text":"opened"}],"answer":"A","explanation":"本题涉及情态动词知识点。正确答案是A：open。"}
  {"id":"english-g5-019","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["定语从句"],"question":"The book _____ cover is red is mine.","options":[{"label":"A","text":"whose"},{"label":"B","text":"which"},{"label":"C","text":"who"},{"label":"D","text":"whom"}],"answer":"A","explanation":"本题涉及定语从句知识点。正确答案是A：whose。"}
  {"id":"english-g5-020","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["宾语从句"],"question":"He asked me _____ I was busy.","options":[{"label":"A","text":"if"},{"label":"B","text":"that"},{"label":"C","text":"what"},{"label":"D","text":"which"}],"answer":"A","explanation":"本题涉及宾语从句知识点。正确答案是A：if。"}
  {"id":"english-g5-035","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["现在进行时"],"question":"Which of the following is correct about 现在进行时?","options":[{"label":"A","text":"现在进行时 is an important part of 语法基础"},{"label":"B","text":"现在进行时 belongs to another category"},{"label":"C","text":"现在进行时 is not related to 语法基础"},{"label":"D","text":"现在进行时 is only used in special situations"}],"answer":"A","explanation":"现在进行时是语法基础学习中的重要内容。"}
  {"id":"english-g5-036","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["现在进行时"],"question":"Which of the following is correct about 现在进行时?","options":[{"label":"A","text":"现在进行时 is an important part of 语法基础"},{"label":"B","text":"现在进行时 belongs to another category"},{"label":"C","text":"现在进行时 is not related to 语法基础"},{"label":"D","text":"现在进行时 is only used in special situations"}],"answer":"A","explanation":"现在进行时是语法基础学习中的重要内容。"}
  {"id":"english-g5-038","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["一般现在时"],"question":"Which of the following is correct about 一般现在时?","options":[{"label":"A","text":"一般现在时 is an important part of 语法基础"},{"label":"B","text":"一般现在时 belongs to another category"},{"label":"C","text":"一般现在时 is not related to 语法基础"},{"label":"D","text":"一般现在时 is only used in special situations"}],"answer":"A","explanation":"一般现在时是语法基础学习中的重要内容。"}
  {"id":"english-g5-039","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["一般现在时"],"question":"Which of the following is correct about 一般现在时?","options":[{"label":"A","text":"一般现在时 is an important part of 语法基础"},{"label":"B","text":"一般现在时 belongs to another category"},{"label":"C","text":"一般现在时 is not related to 语法基础"},{"label":"D","text":"一般现在时 is only used in special situations"}],"answer":"A","explanation":"一般现在时是语法基础学习中的重要内容。"}
  {"id":"english-g5-041","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["可数名词"],"question":"Which of the following is correct about 可数名词?","options":[{"label":"A","text":"可数名词 is an important part of 语法基础"},{"label":"B","text":"可数名词 belongs to another category"},{"label":"C","text":"可数名词 is not related to 语法基础"},{"label":"D","text":"可数名词 is only used in special situations"}],"answer":"A","explanation":"可数名词是语法基础学习中的重要内容。"}
  {"id":"english-g5-042","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["可数名词"],"question":"Which of the following is correct about 可数名词?","options":[{"label":"A","text":"可数名词 is an important part of 语法基础"},{"label":"B","text":"可数名词 belongs to another category"},{"label":"C","text":"可数名词 is not related to 语法基础"},{"label":"D","text":"可数名词 is only used in special situations"}],"answer":"A","explanation":"可数名词是语法基础学习中的重要内容。"}
  {"id":"english-g5-044","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["形容词比较级"],"question":"Which of the following is correct about 形容词比较级?","options":[{"label":"A","text":"形容词比较级 is an important part of 语法基础"},{"label":"B","text":"形容词比较级 belongs to another category"},{"label":"C","text":"形容词比较级 is not related to 语法基础"},{"label":"D","text":"形容词比较级 is only used in special situations"}],"answer":"A","explanation":"形容词比较级是语法基础学习中的重要内容。"}
  {"id":"english-g5-045","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["形容词比较级"],"question":"Which of the following is correct about 形容词比较级?","options":[{"label":"A","text":"形容词比较级 is an important part of 语法基础"},{"label":"B","text":"形容词比较级 belongs to another category"},{"label":"C","text":"形容词比较级 is not related to 语法基础"},{"label":"D","text":"形容词比较级 is only used in special situations"}],"answer":"A","explanation":"形容词比较级是语法基础学习中的重要内容。"}
  {"id":"english-g5-047","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["there be句型"],"question":"Which of the following is correct about there be句型?","options":[{"label":"A","text":"there be句型 is an important part of 语法基础"},{"label":"B","text":"there be句型 belongs to another category"},{"label":"C","text":"there be句型 is not related to 语法基础"},{"label":"D","text":"there be句型 is only used in special situations"}],"answer":"A","explanation":"there be句型是语法基础学习中的重要内容。"}
  {"id":"english-g5-048","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["there be句型"],"question":"Which of the following is correct about there be句型?","options":[{"label":"A","text":"there be句型 is an important part of 语法基础"},{"label":"B","text":"there be句型 belongs to another category"},{"label":"C","text":"there be句型 is not related to 语法基础"},{"label":"D","text":"there be句型 is only used in special situations"}],"answer":"A","explanation":"there be句型是语法基础学习中的重要内容。"}
  {"id":"english-g5-050","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["情态动词can"],"question":"Which of the following is correct about 情态动词can?","options":[{"label":"A","text":"情态动词can is an important part of 语法基础"},{"label":"B","text":"情态动词can belongs to another category"},{"label":"C","text":"情态动词can is not related to 语法基础"},{"label":"D","text":"情态动词can is only used in special situations"}],"answer":"A","explanation":"情态动词can是语法基础学习中的重要内容。"}
  {"id":"english-g5-051","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["情态动词can"],"question":"Which of the following is correct about 情态动词can?","options":[{"label":"A","text":"情态动词can is an important part of 语法基础"},{"label":"B","text":"情态动词can belongs to another category"},{"label":"C","text":"情态动词can is not related to 语法基础"},{"label":"D","text":"情态动词can is only used in special situations"}],"answer":"A","explanation":"情态动词can是语法基础学习中的重要内容。"}
  {"id":"english-g5-053","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["特殊疑问词"],"question":"Which of the following is correct about 特殊疑问词?","options":[{"label":"A","text":"特殊疑问词 is an important part of 语法基础"},{"label":"B","text":"特殊疑问词 belongs to another category"},{"label":"C","text":"特殊疑问词 is not related to 语法基础"},{"label":"D","text":"特殊疑问词 is only used in special situations"}],"answer":"A","explanation":"特殊疑问词是语法基础学习中的重要内容。"}
  {"id":"english-g5-054","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["特殊疑问词"],"question":"Which of the following is correct about 特殊疑问词?","options":[{"label":"A","text":"特殊疑问词 is an important part of 语法基础"},{"label":"B","text":"特殊疑问词 belongs to another category"},{"label":"C","text":"特殊疑问词 is not related to 语法基础"},{"label":"D","text":"特殊疑问词 is only used in special situations"}],"answer":"A","explanation":"特殊疑问词是语法基础学习中的重要内容。"}
  {"id":"english-g5-056","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["天气预报"],"question":"Which of the following is correct about 天气预报?","options":[{"label":"A","text":"天气预报 is an important part of 口语交际"},{"label":"B","text":"天气预报 belongs to another category"},{"label":"C","text":"天气预报 is not related to 口语交际"},{"label":"D","text":"天气预报 is only used in special situations"}],"answer":"A","explanation":"天气预报是口语交际学习中的重要内容。"}
  {"id":"english-g5-057","type":"choice","subject":"english","difficulty":medium,"grade":5,"knowledgeTags":["天气预报"],"question":"Which of the following is correct about 天气预报?","options":[{"label":"A","text":"天气预报 is an important part of 口语交际"},{"label":"B","text":"天气预报 belongs to another category"},{"label":"C","text":"天气预报 is not related to 口语交际"},{"label":"D","text":"天气预报 is only used in special situations"}],"answer":"A","explanation":"天气预报是口语交际学习中的重要内容。"}
  {"id":"english-g6-001","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["字母认知"],"question":"Which is a capital letter?","options":[{"label":"A","text":"a"},{"label":"B","text":"B"},{"label":"C","text":"c"},{"label":"D","text":"d"}],"answer":"B","explanation":"本题涉及字母认知知识点。正确答案是B：B。"}
  {"id":"english-g6-002","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["词汇识记"],"question":"What does 'apple' mean?","options":[{"label":"A","text":"苹果"},{"label":"B","text":"香蕉"},{"label":"C","text":"橙子"},{"label":"D","text":"葡萄"}],"answer":"A","explanation":"本题涉及词汇识记知识点。正确答案是A：苹果。"}
  {"id":"english-g6-003","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["词汇拼写"],"question":"Choose the correct spelling:","options":[{"label":"A","text":"elephnt"},{"label":"B","text":"elephant"},{"label":"C","text":"elephent"},{"label":"D","text":"elefaunt"}],"answer":"B","explanation":"本题涉及词汇拼写知识点。正确答案是B：elephant。"}
  {"id":"english-g6-004","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["名词单复数"],"question":"He is a _____ (boy).","options":[{"label":"A","text":"girl"},{"label":"B","text":"boy"},{"label":"C","text":"teacher"},{"label":"D","text":"doctor"}],"answer":"B","explanation":"本题涉及名词单复数知识点。正确答案是B：boy。"}
  {"id":"english-g6-005","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["日常用语"],"question":"How are you? I am _____.","options":[{"label":"A","text":"sad"},{"label":"B","text":"fine"},{"label":"C","text":"cry"},{"label":"D","text":"bad"}],"answer":"B","explanation":"本题涉及日常用语知识点。正确答案是B：fine。"}
  {"id":"english-g6-006","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["词汇反义词"],"question":"What is the opposite of 'big'?","options":[{"label":"A","text":"small"},{"label":"B","text":"tall"},{"label":"C","text":"long"},{"label":"D","text":"short"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：small。"}
  {"id":"english-g6-007","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["一般现在时"],"question":"She _____ apples every day.","options":[{"label":"A","text":"eat"},{"label":"B","text":"eats"},{"label":"C","text":"eating"},{"label":"D","text":"ate"}],"answer":"B","explanation":"本题涉及一般现在时知识点。正确答案是B：eats。"}
  {"id":"english-g6-008","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["特殊疑问句"],"question":"_____ is your name? My name is Tom.","options":[{"label":"A","text":"What"},{"label":"B","text":"Who"},{"label":"C","text":"Where"},{"label":"D","text":"When"}],"answer":"A","explanation":"本题涉及特殊疑问句知识点。正确答案是A：What。"}
  {"id":"english-g6-009","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["可数不可数名词"],"question":"How many _____ (month) in a year?","options":[{"label":"A","text":"month"},{"label":"B","text":"months"},{"label":"C","text":"monthes"},{"label":"D","text":"monthed"}],"answer":"B","explanation":"本题涉及可数不可数名词知识点。正确答案是B：months。"}
  {"id":"english-g6-010","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["介词用法"],"question":"The cat is on the _____.","options":[{"label":"A","text":"desk"},{"label":"B","text":"table"},{"label":"C","text":"chair"},{"label":"D","text":"sofa"}],"answer":"A","explanation":"本题涉及介词用法知识点。正确答案是A：desk。"}
  {"id":"english-g6-011","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["there be句型"],"question":"There _____ some water in the glass.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}],"answer":"A","explanation":"本题涉及there be句型知识点。正确答案是A：is。"}
  {"id":"english-g6-012","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["名词变复数"],"question":"I have two _____ (child).","options":[{"label":"A","text":"child"},{"label":"B","text":"childs"},{"label":"C","text":"children"},{"label":"D","text":"childes"}],"answer":"C","explanation":"本题涉及名词变复数知识点。正确答案是C：children。"}
  {"id":"english-g6-013","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["比较级"],"question":"He is _____ than his brother.","options":[{"label":"A","text":"tall"},{"label":"B","text":"taller"},{"label":"C","text":"tallest"},{"label":"D","text":"more tall"}],"answer":"B","explanation":"本题涉及比较级知识点。正确答案是B：taller。"}
  {"id":"english-g6-014","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["词汇反义词"],"question":"The opposite of 'hot' is _____.","options":[{"label":"A","text":"cold"},{"label":"B","text":"warm"},{"label":"C","text":"cool"},{"label":"D","text":"wet"}],"answer":"A","explanation":"本题涉及词汇反义词知识点。正确答案是A：cold。"}
  {"id":"english-g6-015","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["数词用法"],"question":"There are _____ days in a week.","options":[{"label":"A","text":"five"},{"label":"B","text":"six"},{"label":"C","text":"seven"},{"label":"D","text":"eight"}],"answer":"C","explanation":"本题涉及数词用法知识点。正确答案是C：seven。"}
  {"id":"english-g6-016","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["句型辨析"],"question":"Which sentence is correct?","options":[{"label":"A","text":"He don't like fish."},{"label":"B","text":"He doesn't like fish."},{"label":"C","text":"He not like fish."},{"label":"D","text":"He no like fish."}],"answer":"B","explanation":"本题涉及句型辨析知识点。正确答案是B：He doesn't like fish.。"}
  {"id":"english-g6-017","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["现在完成时"],"question":"She has lived in Shanghai _____ five years.","options":[{"label":"A","text":"for"},{"label":"B","text":"since"},{"label":"C","text":"in"},{"label":"D","text":"at"}],"answer":"A","explanation":"本题涉及现在完成时知识点。正确答案是A：for。"}
  {"id":"english-g6-018","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["情态动词"],"question":"Could you please _____ the door?","options":[{"label":"A","text":"open"},{"label":"B","text":"to open"},{"label":"C","text":"opening"},{"label":"D","text":"opened"}],"answer":"A","explanation":"本题涉及情态动词知识点。正确答案是A：open。"}
  {"id":"english-g6-019","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["定语从句"],"question":"The book _____ cover is red is mine.","options":[{"label":"A","text":"whose"},{"label":"B","text":"which"},{"label":"C","text":"who"},{"label":"D","text":"whom"}],"answer":"A","explanation":"本题涉及定语从句知识点。正确答案是A：whose。"}
  {"id":"english-g6-020","type":"choice","subject":"english","difficulty":1,"grade":6,"knowledgeTags":["宾语从句"],"question":"He asked me _____ I was busy.","options":[{"label":"A","text":"if"},{"label":"B","text":"that"},{"label":"C","text":"what"},{"label":"D","text":"which"}],"answer":"A","explanation":"本题涉及宾语从句知识点。正确答案是A：if。"}
  {"id":"english-g6-035","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["过去式基础"],"question":"Which of the following is correct about 过去式基础?","options":[{"label":"A","text":"过去式基础 is an important part of 语法基础"},{"label":"B","text":"过去式基础 belongs to another category"},{"label":"C","text":"过去式基础 is not related to 语法基础"},{"label":"D","text":"过去式基础 is only used in special situations"}],"answer":"A","explanation":"过去式基础是语法基础学习中的重要内容。"}
  {"id":"english-g6-036","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["过去式基础"],"question":"Which of the following is correct about 过去式基础?","options":[{"label":"A","text":"过去式基础 is an important part of 语法基础"},{"label":"B","text":"过去式基础 belongs to another category"},{"label":"C","text":"过去式基础 is not related to 语法基础"},{"label":"D","text":"过去式基础 is only used in special situations"}],"answer":"A","explanation":"过去式基础是语法基础学习中的重要内容。"}
  {"id":"english-g6-038","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["一般过去时"],"question":"Which of the following is correct about 一般过去时?","options":[{"label":"A","text":"一般过去时 is an important part of 语法基础"},{"label":"B","text":"一般过去时 belongs to another category"},{"label":"C","text":"一般过去时 is not related to 语法基础"},{"label":"D","text":"一般过去时 is only used in special situations"}],"answer":"A","explanation":"一般过去时是语法基础学习中的重要内容。"}
  {"id":"english-g6-039","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["一般过去时"],"question":"Which of the following is correct about 一般过去时?","options":[{"label":"A","text":"一般过去时 is an important part of 语法基础"},{"label":"B","text":"一般过去时 belongs to another category"},{"label":"C","text":"一般过去时 is not related to 语法基础"},{"label":"D","text":"一般过去时 is only used in special situations"}],"answer":"A","explanation":"一般过去时是语法基础学习中的重要内容。"}
  {"id":"english-g6-041","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["形容词副词"],"question":"Which of the following is correct about 形容词副词?","options":[{"label":"A","text":"形容词副词 is an important part of 语法基础"},{"label":"B","text":"形容词副词 belongs to another category"},{"label":"C","text":"形容词副词 is not related to 语法基础"},{"label":"D","text":"形容词副词 is only used in special situations"}],"answer":"A","explanation":"形容词副词是语法基础学习中的重要内容。"}
  {"id":"english-g6-042","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["形容词副词"],"question":"Which of the following is correct about 形容词副词?","options":[{"label":"A","text":"形容词副词 is an important part of 语法基础"},{"label":"B","text":"形容词副词 belongs to another category"},{"label":"C","text":"形容词副词 is not related to 语法基础"},{"label":"D","text":"形容词副词 is only used in special situations"}],"answer":"A","explanation":"形容词副词是语法基础学习中的重要内容。"}
  {"id":"english-g6-044","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["方位表达"],"question":"Which of the following is correct about 方位表达?","options":[{"label":"A","text":"方位表达 is an important part of 口语交际"},{"label":"B","text":"方位表达 belongs to another category"},{"label":"C","text":"方位表达 is not related to 口语交际"},{"label":"D","text":"方位表达 is only used in special situations"}],"answer":"A","explanation":"方位表达是口语交际学习中的重要内容。"}
  {"id":"english-g6-045","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["方位表达"],"question":"Which of the following is correct about 方位表达?","options":[{"label":"A","text":"方位表达 is an important part of 口语交际"},{"label":"B","text":"方位表达 belongs to another category"},{"label":"C","text":"方位表达 is not related to 口语交际"},{"label":"D","text":"方位表达 is only used in special situations"}],"answer":"A","explanation":"方位表达是口语交际学习中的重要内容。"}
  {"id":"english-g6-047","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["将来时will"],"question":"Which of the following is correct about 将来时will?","options":[{"label":"A","text":"将来时will is an important part of 语法基础"},{"label":"B","text":"将来时will belongs to another category"},{"label":"C","text":"将来时will is not related to 语法基础"},{"label":"D","text":"将来时will is only used in special situations"}],"answer":"A","explanation":"将来时will是语法基础学习中的重要内容。"}
  {"id":"english-g6-048","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["将来时will"],"question":"Which of the following is correct about 将来时will?","options":[{"label":"A","text":"将来时will is an important part of 语法基础"},{"label":"B","text":"将来时will belongs to another category"},{"label":"C","text":"将来时will is not related to 语法基础"},{"label":"D","text":"将来时will is only used in special situations"}],"answer":"A","explanation":"将来时will是语法基础学习中的重要内容。"}
  {"id":"english-g6-050","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["祈使句"],"question":"Which of the following is correct about 祈使句?","options":[{"label":"A","text":"祈使句 is an important part of 语法基础"},{"label":"B","text":"祈使句 belongs to another category"},{"label":"C","text":"祈使句 is not related to 语法基础"},{"label":"D","text":"祈使句 is only used in special situations"}],"answer":"A","explanation":"祈使句是语法基础学习中的重要内容。"}
  {"id":"english-g6-051","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["祈使句"],"question":"Which of the following is correct about 祈使句?","options":[{"label":"A","text":"祈使句 is an important part of 语法基础"},{"label":"B","text":"祈使句 belongs to another category"},{"label":"C","text":"祈使句 is not related to 语法基础"},{"label":"D","text":"祈使句 is only used in special situations"}],"answer":"A","explanation":"祈使句是语法基础学习中的重要内容。"}
  {"id":"english-g6-053","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["阅读理解"],"question":"Which of the following is correct about 阅读理解?","options":[{"label":"A","text":"阅读理解 is an important part of 阅读理解"},{"label":"B","text":"阅读理解 belongs to another category"},{"label":"C","text":"阅读理解 is not related to 阅读理解"},{"label":"D","text":"阅读理解 is only used in special situations"}],"answer":"A","explanation":"阅读理解是阅读理解学习中的重要内容。"}
  {"id":"english-g6-054","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["阅读理解"],"question":"Which of the following is correct about 阅读理解?","options":[{"label":"A","text":"阅读理解 is an important part of 阅读理解"},{"label":"B","text":"阅读理解 belongs to another category"},{"label":"C","text":"阅读理解 is not related to 阅读理解"},{"label":"D","text":"阅读理解 is only used in special situations"}],"answer":"A","explanation":"阅读理解是阅读理解学习中的重要内容。"}
  {"id":"english-g6-056","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["写作训练"],"question":"Which of the following is correct about 写作训练?","options":[{"label":"A","text":"写作训练 is an important part of 写作训练"},{"label":"B","text":"写作训练 belongs to another category"},{"label":"C","text":"写作训练 is not related to 写作训练"},{"label":"D","text":"写作训练 is only used in special situations"}],"answer":"A","explanation":"写作训练是写作训练学习中的重要内容。"}
  {"id":"english-g6-057","type":"choice","subject":"english","difficulty":medium,"grade":6,"knowledgeTags":["写作训练"],"question":"Which of the following is correct about 写作训练?","options":[{"label":"A","text":"写作训练 is an important part of 写作训练"},{"label":"B","text":"写作训练 belongs to another category"},{"label":"C","text":"写作训练 is not related to 写作训练"},{"label":"D","text":"写作训练 is only used in special situations"}],"answer":"A","explanation":"写作训练是写作训练学习中的重要内容。"}
  {"id":"primary-english-001","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇"],"question":"Hello! How are you?","options":[{"label":"A","text":"I'm fine, thank you."},{"label":"B","text":"I'm 10 years old."},{"label":"C","text":"I'm a student."},{"label":"D","text":"Nice to meet you."}],"answer":"A","explanation":"这是常见的问候回答。"}
  {"id":"primary-english-002","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇"],"question":"What is this?","options":[{"label":"A","text":"It's a book."},{"label":"B","text":"It's red."},{"label":"C","text":"I like it."},{"label":"D","text":"Yes, it is."}],"answer":"A","explanation":"this是指示代词，用于指代近处的事物。"}
  {"id":"primary-english-003","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["词汇"],"question":"How old are you?","options":[{"label":"A","text":"I'm 9."},{"label":"B","text":"I'm a boy."},{"label":"C","text":"I'm happy."},{"label":"D","text":"I'm in Class 3."}],"answer":"A","explanation":"How old用于询问年龄。"}
  {"id":"primary-english-004","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["颜色"],"question":"What color is the sky?","options":[{"label":"A","text":"Blue."},{"label":"B","text":"Red."},{"label":"C","text":"Green."},{"label":"D","text":"Yellow."}],"answer":"A","explanation":"天空是蓝色的。"}
  {"id":"primary-english-005","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["动物"],"question":"What animal says 'woof woof'?","options":[{"label":"A","text":"Dog."},{"label":"B","text":"Cat."},{"label":"C","text":"Bird."},{"label":"D","text":"Fish."}],"answer":"A","explanation":"狗的叫声是woof woof。"}
  {"id":"primary-english-006","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["食物"],"question":"I like _______ for breakfast.","options":[{"label":"A","text":"bread"},{"label":"B","text":"book"},{"label":"C","text":"chair"},{"label":"D","text":"desk"}],"answer":"A","explanation":"早餐喜欢吃面包。"}
  {"id":"primary-english-007","type":"choice","subject":"english","difficulty":1,"grade":3,"knowledgeTags":["家庭"],"question":"This is my mother. She is a _______.","options":[{"label":"A","text":"teacher"},{"label":"B","text":"doctor"},{"label":"C","text":"nurse"},{"label":"D","text":"driver"}],"answer":"A","explanation":"职业名称识别。"}
  {"id":"primary-english-008","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["时间"],"question":"What time is it?","options":[{"label":"A","text":"It's 8 o'clock."},{"label":"B","text":"It's Monday."},{"label":"C","text":"It's sunny."},{"label":"D","text":"It's a book."}],"answer":"A","explanation":"询问时间用What time。"}
  {"id":"primary-english-009","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["星期"],"question":"Today is Friday. Tomorrow is _______.","options":[{"label":"A","text":"Saturday"},{"label":"B","text":"Sunday"},{"label":"C","text":"Monday"},{"label":"D","text":"Thursday"}],"answer":"A","explanation":"星期五是Friday，周六是Saturday。"}
  {"id":"primary-english-010","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["月份"],"question":"There are _______ months in a year.","options":[{"label":"A","text":"twelve"},{"label":"B","text":"ten"},{"label":"C","text":"seven"},{"label":"D","text":"five"}],"answer":"A","explanation":"一年有12个月。"}
  {"id":"primary-english-011","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["季节"],"question":"In summer, it is very _______.","options":[{"label":"A","text":"hot"},{"label":"B","text":"cold"},{"label":"C","text":"snowy"},{"label":"D","text":"cool"}],"answer":"A","explanation":"夏天很热。"}
  {"id":"primary-english-012","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["数字"],"question":"Five + three = _______.","options":[{"label":"A","text":"eight"},{"label":"B","text":"two"},{"label":"C","text":"fifteen"},{"label":"D","text":"four"}],"answer":"A","explanation":"5+3=8。"}
  {"id":"primary-english-013","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["数字"],"question":"Twelve - four = _______.","options":[{"label":"A","text":"eight"},{"label":"B","text":"sixteen"},{"label":"C","text":"three"},{"label":"D","text":"eighteen"}],"answer":"A","explanation":"12-4=8。"}
  {"id":"primary-english-014","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["介词"],"question":"The cat is _______ the table.","options":[{"label":"A","text":"under"},{"label":"B","text":"in"},{"label":"C","text":"on"},{"label":"D","text":"to"}],"answer":"A","explanation":"猫在桌子下面。"}
  {"id":"primary-english-015","type":"choice","subject":"english","difficulty":1,"grade":4,"knowledgeTags":["方位"],"question":"The school is _______ my house.","options":[{"label":"A","text":"near"},{"label":"B","text":"under"},{"label":"C","text":"in"},{"label":"D","text":"behind"}],"answer":"A","explanation":"学校在房子附近。"}
  {"id":"primary-english-016","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["现在进行时"],"question":"Look! The children _______ in the park.","options":[{"label":"A","text":"are playing"},{"label":"B","text":"play"},{"label":"C","text":"played"},{"label":"D","text":"is playing"}],"answer":"A","explanation":"Look提示进行时，多个孩子用are。"}
  {"id":"primary-english-017","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["be动词"],"question":"There _______ some water in the glass.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}],"answer":"A","explanation":"water是不可数名词，用is。"}
  {"id":"primary-english-018","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["可数名词"],"question":"I have two _______.","options":[{"label":"A","text":"apples"},{"label":"B","text":"water"},{"label":"C","text":"milk"},{"label":"D","text":"bread"}],"answer":"A","explanation":"apples是可数名词复数。"}
  {"id":"primary-english-019","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["第三人称单数"],"question":"She _______ English very well.","options":[{"label":"A","text":"speaks"},{"label":"B","text":"speak"},{"label":"C","text":"speaking"},{"label":"D","text":"spoke"}],"answer":"A","explanation":"she是第三人称单数，动词加s。"}
  {"id":"primary-english-020","type":"choice","subject":"english","difficulty":1,"grade":5,"knowledgeTags":["like加ing"],"question":"My brother likes _______ football.","options":[{"label":"A","text":"playing"},{"label":"B","text":"play"},{"label":"C","text":"plays"},{"label":"D","text":"played"}],"answer":"A","explanation":"like后加动词ing形式。"}
  {"id":"primary-english-021","type":"choice","subject":"english","difficulty":2,"grade":5,"knowledgeTags":["情态动词"],"question":"_______ I use your pen?","options":[{"label":"A","text":"May"},{"label":"B","text":"Am"},{"label":"C","text":"Is"},{"label":"D","text":"Are"}],"answer":"A","explanation":"May用于请求许可。"}
  {"id":"primary-english-022","type":"choice","subject":"english","difficulty":2,"grade":5,"knowledgeTags":["there be"],"question":"There _______ a book and two pencils on the desk.","options":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"be"}],"answer":"A","explanation":"there be就近原则，a book是单数。"}
  {"id":"primary-english-023","type":"choice","subject":"english","difficulty":2,"grade":5,"knowledgeTags":["特殊疑问句"],"question":"_______ did you go last Sunday?","options":[{"label":"A","text":"Where"},{"label":"B","text":"What"},{"label":"C","text":"When"},{"label":"D","text":"How"}],"answer":"A","explanation":"last Sunday提示地点，用Where。"}
  {"id":"primary-english-024","type":"choice","subject":"english","difficulty":2,"grade":5,"knowledgeTags":["形容词性物主代词"],"question":"This is _______ book. It is _______ book.","options":[{"label":"A","text":"my / my"},{"label":"B","text":"I / my"},{"label":"C","text":"my / me"},{"label":"D","text":"me / my"}],"answer":"A","explanation":"形容词性物主代词修饰名词。"}
  {"id":"primary-english-025","type":"choice","subject":"english","difficulty":2,"grade":5,"knowledgeTags":["名词所有格"],"question":"This is Tom _______ room.","options":[{"label":"A","text":"'s"},{"label":"B","text":"s'"},{"label":"C","text":"s"},{"label":"D","text":"'"}],"answer":"A","explanation":"Tom的房间用Tom's表示所有格。"}
  {"id":"primary-english-026","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["一般过去时"],"question":"She _______ to school yesterday.","options":[{"label":"A","text":"went"},{"label":"B","text":"go"},{"label":"C","text":"going"},{"label":"D","text":"goes"}],"answer":"A","explanation":"yesterday是一般过去时标志。"}
  {"id":"primary-english-027","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["规则动词过去式"],"question":"We _______ a good time last night.","options":[{"label":"A","text":"had"},{"label":"B","text":"have"},{"label":"C","text":"has"},{"label":"D","text":"having"}],"answer":"A","explanation":"last night是过去时间，have的过去式是had。"}
  {"id":"primary-english-028","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["一般将来时"],"question":"I _______ go to Beijing next week.","options":[{"label":"A","text":"will"},{"label":"B","text":"am going to"},{"label":"C","text":"both A and B"},{"label":"D","text":"not going to"}],"answer":"C","explanation":"will和be going to都可以表示将来。"}
  {"id":"primary-english-029","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["some/any"],"question":"Are there _______ apples on the table?","options":[{"label":"A","text":"any"},{"label":"B","text":"some"},{"label":"C","text":"a"},{"label":"D","text":"an"}],"answer":"A","explanation":"一般疑问句中用any。"}
  {"id":"primary-english-030","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["比较级"],"question":"Tom is _______ than Jim.","options":[{"label":"A","text":"taller"},{"label":"B","text":"tall"},{"label":"C","text":"tallest"},{"label":"D","text":"more tall"}],"answer":"A","explanation":"than提示比较级，tall的比较级是taller。"}
  {"id":"primary-english-031","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["反义词"],"question":"The sun rises in the east and sets in the _______.","options":[{"label":"A","text":"west"},{"label":"B","text":"south"},{"label":"C","text":"north"},{"label":"D","text":"up"}],"answer":"A","explanation":"太阳东升西落。"}
  {"id":"primary-english-032","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["频度副词"],"question":"I _______ eat junk food. It's unhealthy.","options":[{"label":"A","text":"never"},{"label":"B","text":"always"},{"label":"C","text":"usually"},{"label":"D","text":"often"}],"answer":"A","explanation":"从不吃不健康食品。"}
  {"id":"primary-english-033","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["现在完成时"],"question":"I have _______ finished my homework.","options":[{"label":"A","text":"already"},{"label":"B","text":"still"},{"label":"C","text":"yet"},{"label":"D","text":"again"}],"answer":"A","explanation":"already用于现在完成时肯定句。"}
  {"id":"primary-english-034","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["祈使句"],"question":"_______ late for school again!","options":[{"label":"A","text":"Don't be"},{"label":"B","text":"Be not"},{"label":"C","text":"Not be"},{"label":"D","text":"Don't"}],"answer":"A","explanation":"否定祈使句用Don't + be。"}
  {"id":"primary-english-035","type":"choice","subject":"english","difficulty":2,"grade":6,"knowledgeTags":["too/to"],"question":"The box is too heavy _______ carry.","options":[{"label":"A","text":"to"},{"label":"B","text":"for"},{"label":"C","text":"too"},{"label":"D","text":"and"}],"answer":"A","explanation":"too...to...太...而不能..."}
  {"id":"primary-english-036","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读理解"],"question":"What is the main idea of the passage?","options":[{"label":"A","text":"About animals."},{"label":"B","text":"About plants."},{"label":"C","text":"About weather."},{"label":"D","text":"About food."}],"answer":"A","explanation":"根据文章内容判断主题。"}
  {"id":"primary-english-037","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["词义推断"],"question":"The word 'brave' in the sentence means _______.","options":[{"label":"A","text":"勇敢的"},{"label":"B","text":"聪明的"},{"label":"C","text":"善良的"},{"label":"D","text":"诚实的"}],"answer":"A","explanation":"根据上下文推断词义。"}
  {"id":"primary-english-038","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["排序"],"question":"Which sentence comes first?","options":[{"label":"A","text":"First"},{"label":"B","text":"Second"},{"label":"C","text":"Third"},{"label":"D","text":"Fourth"}],"answer":"A","explanation":"根据逻辑顺序判断。"}
  {"id":"primary-english-039","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["口语交际"],"question":"When someone says 'Thank you!', you should reply _______.","options":[{"label":"A","text":"You're welcome."},{"label":"B","text":"Sorry."},{"label":"C","text":"Excuse me."},{"label":"D","text":"That's OK."}],"answer":"A","explanation":"礼貌回应感谢。"}
  {"id":"primary-english-040","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读细节"],"question":"How many children are there in the story?","options":[{"label":"A","text":"Three."},{"label":"B","text":"Four."},{"label":"C","text":"Five."},{"label":"D","text":"Six."}],"answer":"A","explanation":"在文章中找到具体数字。"}
  {"id":"primary-english-041","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["完形填空"],"question":"Please _______ the window. It's cold.","options":[{"label":"A","text":"close"},{"label":"B","text":"open"},{"label":"C","text":"clean"},{"label":"D","text":"wash"}],"answer":"A","explanation":"冷的时候要关窗户。"}
  {"id":"primary-english-042","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读排序"],"question":"What happened first in the story?","options":[{"label":"A","text":"The boy woke up early in the morning."},{"label":"B","text":"The boy went to school with his backpack."},{"label":"C","text":"The boy attended an English class."},{"label":"D","text":"The boy played football after class."}],"answer":"A","explanation":"根据时间顺序判断先后。"}
  {"id":"primary-english-043","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读推断"],"question":"We can infer that _______.","options":[{"label":"A","text":"A"},{"label":"B","text":"B"},{"label":"C","text":"C"},{"label":"D","text":"D"}],"answer":"A","explanation":"根据文章信息进行推断。"}
  {"id":"primary-english-044","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["首字母填空"],"question":"It is s_______ in winter.","options":[{"label":"A","text":"snowy"},{"label":"B","text":"sunny"},{"label":"C","text":"windy"},{"label":"D","text":"cloudy"}],"answer":"A","explanation":"冬天是下雪的。"}
  {"id":"primary-english-045","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["选词填空"],"question":"I would like some _______.","options":[{"label":"A","text":"juice"},{"label":"B","text":"book"},{"label":"C","text":"desk"},{"label":"D","text":"chair"}],"answer":"A","explanation":"would like后加名词饮品。"}
  {"id":"primary-english-046","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读判断"],"question":"Is the following statement TRUE or FALSE?","options":[{"label":"A","text":"True."},{"label":"B","text":"False."},{"label":"C","text":"Not mentioned."},{"label":"D","text":"Both."}],"answer":"A","explanation":"根据文章信息判断正误。"}
  {"id":"primary-english-047","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["情景交际"],"question":"Your friend is sick. You should say _______.","options":[{"label":"A","text":"Hope you get better soon!"},{"label":"B","text":"Happy birthday!"},{"label":"C","text":"Congratulations!"},{"label":"D","text":"Good luck!"}],"answer":"A","explanation":"朋友生病时的问候。"}
  {"id":"primary-english-048","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["阅读推理"],"question":"The story mainly tells us _______.","options":[{"label":"A","text":"A"},{"label":"B","text":"B"},{"label":"C","text":"C"},{"label":"D","text":"D"}],"answer":"A","explanation":"概括文章主旨大意。"}
  {"id":"primary-english-049","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["写作排序"],"question":"Which is the best title for the passage?","options":[{"label":"A","text":"A"},{"label":"B","text":"B"},{"label":"C","text":"C"},{"label":"D","text":"D"}],"answer":"A","explanation":"选择最恰当的标题。"}
  {"id":"primary-english-050","type":"choice","subject":"english","difficulty":3,"grade":6,"knowledgeTags":["综合运用"],"question":"According to the passage, we should _______.","options":[{"label":"A","text":"A"},{"label":"B","text":"B"},{"label":"C","text":"C"},{"label":"D","text":"D"}],"answer":"A","explanation":"综合文章信息得出结论。"}
];